### ISSUE TITLE
Compile On Windows

### ISSUE THREAD

**Issue by reaperhulk** [pyca/pynacl#100]
Right now pynacl won't compile on windows. We should fix that!

**Comment by cbrunker** [comment]
Working Build
-----------------
The last entry on this issue was very close, just needed to use something like Dependency Walker on the .pyd file to find out what was missing.

Quick and dirty build instructions for Windows 32bit and Python 3.4.2 are below, this is using Visual Studio 2010 Express, and PyNaCl git snapshot as of 12th Jan 2015. 

Test was successfully completed in a Windows 8.1 64bit environment.

Attempts were made using Mingw, however Mingw does not play nicely with cffi it seems.

Setup
-----
* Edit MANIFEST.in and remove SODIUM references
* (Optional) Remove packaged sodium source
* Download pre-built libraries for libsodium and Visual Studio
* Install Visual Studio Express 2010 (which python 3.4 is built against)
* Run cmd.exe and change directory to your PyNaCl source directory

Build
------
* Tell the build script to use pre-built libs
 * set SODIUM_INSTALL=system
* Let cl.exe and link.exe (Visual studio) know where the header and prebuilt libs are
 * set INCLUDE=C:\path\to\libsodium-1.0.1-msv\include
 * set LIB=C:\path\to\libsodium-1.0.1-msvc\Win32\Release\v100\dynamic
* Rename dynamic lib names to 'sodium' instead of 'libsodium'
* Build the code
 * C:\Python34\python.exe setup.py build
* Install the code
 * C:\Python34\python.exe setup.py install

Last Step
----------
The missing step:
* Copy libsodium.dll from the dynamic directory (not the renamed sodium.dll) to the installed site package location's nacl\_lib directory. Example location:
 * C:\Python34\Lib\site-packages\PyNaCl-0.3.0-py3.4-win32.egg\nacl\_lib

**Comment by hoffmabc** [comment]
@cbrunker were you really able to get the code working with this process? I have tried replicating it several times now and it still bombs trying to call sub modules (i.e. import nacl.signing).

**Comment by hoffmabc** [comment]
@Insoleet did you get past this issue? I get the same one.

**Comment by Insoleet** [comment]
I don't pynacl anymore because of this problem. I use "libnacl" now. https://libnacl.readthedocs.org/en/latest/

**Comment by hoffmabc** [comment]
Ok I was able to get that to work. I guess I have to port stuff over to libnacl now.

**Comment by cbrunker** [comment]
@hoffmabc Yes, I have used pynacl for cross platform (Win/Linux) libsodium support for multiple projects now. The initial setup for windows is a pain, however the library works without issue on windows and python 3.4.3

**Comment by hoffmabc** [comment]
Wow I'm still getting the missing module error. I followed your instructions to a T As well.

**Comment by reaperhulk** [comment]
If someone wants to tackle the project to support this seamlessly we're happy to take a patch. The main challenge will really just be untangling the POSIX expectations for the `SODIUM_INSTALL=bundled` case.

One we have it working properly we can do a new release (and I'll be happy to build Windows wheels with static linking like we do for pyca/cryptography).

**Comment by hoffmabc** [comment]
Ok I would love to help on this so I'll see if @cpacia and I can make this happen.

**Comment by hoffmabc** [comment]
Oh @cbrunker just noticed you used python 3.4. Is it possible to build against python 2.7?

**Comment by cbrunker** [comment]
Haven't tried, you'll need to use VS2008 or similar for 2.7 instead of VS2010

**Comment by hoffmabc** [comment]
I got it to work. Once I have a proper instruction set I'll post a link.

**Comment by hoffmabc** [comment]
I've gotten this to work also as an egg zip file as long as you have the Visual C Redistributable installed it works fine.

**Comment by sheilatron** [comment]
Hi @hoffmabc , do you have instructions on building this for Python 2.7?

**Comment by sheilatron** [comment]
> tackle the project to support this seamlessly we're happy to take a patch

@reaperhulk has anyone taken this up?

**Comment by hoffmabc** [comment]
Sorry I will post tomorrow

**Comment by reaperhulk** [comment]
@sheilatron thus far no one has taken on the work to contribute a branch that builds on Windows. PyCA has infrastructure to do windows CI (and to produce and upload windows wheels) if someone contributes the patch, but most of my focus is on https://github.com/pyca/cryptography for now.

It sounds like perhaps @hoffmabc's instructions could be used to create the necessary PR though!

**Comment by cpacia** [comment]
We've been able to get it working on windows for OpenBazaar. Brian can provide detailed instructions.  What are the chances of another release sometime soon? I'd like to use the key conversions in OB.

**Comment by reaperhulk** [comment]
@warner what do you think of trying to do a release in the next few weeks? The accumulated last several months + windows support + the work you were reviewing the other night + the cffi 1.0 conversion (which I need to spend some time on) seems release worthy to me.

**Comment by hoffmabc** [comment]
+1

**Comment by warner** [comment]
+1. I'm travelling a bunch in the next two weeks but I'll try to find some time to look at the current PRs.

**Comment by hoffmabc** [comment]
So I've been trying hard to recode this for Windows, but unfortunately I've realized it still will require a compiler like mingw or Visual C++ and I'm still running into some issues with it finding the dll. 

Here are the instructions to work around it if you want to try them. I will continue working on a code submission though.

https://github.com/OpenBazaar/OpenBazaar-Server/wiki/Installing-pynacl-on-Windows

**Comment by hoffmabc** [comment]
I think the best approach would be to provide a wheel for users to install.

**Comment by sheilatron** [comment]
Thanks @hoffmabc ! We'll try out the instructions.

**Comment by reaperhulk** [comment]
I went ahead and implemented Windows support. The necessary env flags are now in master and I started documenting it in #165. The next release of pynacl (hopefully next week) will ship windows wheels by default for python 2.7, 3.3, 3.4, and 3.5 on both 32-bit and 64-bit python.

**Comment by sheilatron** [comment]
Awesome! Thanks so much!

**Comment by hoffmabc** [comment]
:+1:

**Comment by reaperhulk** [comment]
PyNaCl 1.0.1 ships with wheels for Windows (and OS X) now. 2.7, 3.3, 3.4, and 3.5 supported (and both 32-bit and 64-bit on the Windows side). Future releases will always ship this way. If you run into any problems please open a new issue! :sparkles:

**Comment by AraHaan** [comment]
I am having issues building this with Python 3.6 Alpha 3. It works on python 3.5 however. I get this:
```py
Collecting PyNacl
  Using cached PyNaCl-1.0.1.tar.gz
Requirement already up-to-date: six in e:\users\elsword\desktop\python36-x86\lib
\site-packages (from PyNacl)
Requirement already up-to-date: cffi>=1.1.0 in e:\users\elsword\desktop\python36
-x86\lib\site-packages (from PyNacl)
Requirement already up-to-date: pycparser in e:\users\elsword\desktop\python36-x
86\lib\site-packages (from cffi>=1.1.0->PyNacl)
Installing collected packages: PyNacl
  Running setup.py install for PyNacl ... error
    Complete output from command E:\Users\Elsword\Desktop\python36-x86\python.ex
e -u -c "import setuptools, tokenize;__file__='E:\\Users\\Elsword\\AppData\\Loca
l\\Temp\\pip-build-druf4in4\\PyNacl\\setup.py';exec(compile(getattr(tokenize, 'o
pen', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install
--record E:\Users\Elsword\AppData\Local\Temp\pip-xcnmx096-record\install-record.
txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\nacl
    copying src\nacl\encoding.py -> build\lib.win32-3.6\nacl
    copying src\nacl\exceptions.py -> build\lib.win32-3.6\nacl
    copying src\nacl\hash.py -> build\lib.win32-3.6\nacl
    copying src\nacl\public.py -> build\lib.win32-3.6\nacl
    copying src\nacl\secret.py -> build\lib.win32-3.6\nacl
    copying src\nacl\signing.py -> build\lib.win32-3.6\nacl
    copying src\nacl\utils.py -> build\lib.win32-3.6\nacl
    copying src\nacl\__init__.py -> build\lib.win32-3.6\nacl
    creating build\lib.win32-3.6\nacl\bindings
    copying src\nacl\bindings\crypto_box.py -> build\lib.win32-3.6\nacl\bindings

    copying src\nacl\bindings\crypto_hash.py -> build\lib.win32-3.6\nacl\binding
s
    copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win32-3.6\nacl\b
indings
    copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win32-3.6\nacl\bi
ndings
    copying src\nacl\bindings\crypto_sign.py -> build\lib.win32-3.6\nacl\binding
s
    copying src\nacl\bindings\randombytes.py -> build\lib.win32-3.6\nacl\binding
s
    copying src\nacl\bindings\sodium_core.py -> build\lib.win32-3.6\nacl\binding
s
    copying src\nacl\bindings\__init__.py -> build\lib.win32-3.6\nacl\bindings
    running build_clib
    error: [WinError 193] %1 is not a valid Win32 application

    ----------------------------------------
Command "E:\Users\Elsword\Desktop\python36-x86\python.exe -u -c "import setuptoo
ls, tokenize;__file__='E:\\Users\\Elsword\\AppData\\Local\\Temp\\pip-build-druf4
in4\\PyNacl\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).re
ad().replace('\r\n', '\n'), __file__, 'exec'))" install --record E:\Users\Elswor
d\AppData\Local\Temp\pip-xcnmx096-record\install-record.txt --single-version-ext
ernally-managed --compile" failed with error code 1 in E:\Users\Elsword\AppData\
Local\Temp\pip-build-druf4in4\PyNacl\```

**Comment by AraHaan** [comment]
The reason why I need this is for the pyd's themself I do have the 1.0.1 for 3.5 but the Pyd's will not work on 3.6 Alpha 3 due to it only being able to read 
```
{module name}.cp{python version}-{win32 or amd64}.pyd
```
And so yeah I need this to be able to embed these pyd's in a zip for 3.6 alpha as I perfer the embed versions mostly. (I can generate them myself due to make_zip.py that is only in the python source code.
