### ISSUE TITLE
Provide an example of handling large messages

### ISSUE THREAD

**Issue by ctrtn** [pyca/pynacl#108]
It would be beneficial to have a clear example of handling messages not feasible to load to memory fully: the simplest use case would be encrypting/decrypting a file.

How could the [secret key encryption example](https://pynacl.readthedocs.org/en/latest/secret.html#example) be adapted for file encryption?

Should a file or stream be read in chunks (obviously) and each of the chunk be encrypted with a separate `box.encrypt` call or there's a better way?

**Comment by lmctv** [comment]
Closing, since I think this would get solved as soon as #345 and #347 get implemented
