### ISSUE TITLE
Rename `nacl.c` to something else to avoid silent security failures

### ISSUE THREAD

**Issue by dlitz** [pyca/pynacl#110]
In the upcoming v0.3.0 release, the ordering of arguments in the `crypto_` API is being changed to match upstream.  I suggest also renaming `nacl.c` itself in order to fail loudly for users of that API, rather than quietly changing behavior between releases.

Ideas for the new name:
- `nacl.real`  -- because it's the real nacl interface
- `nacl.crypto`  -- because all of the functions start with `crypto_`
- `nacl.std` -- because it's the standard interface documented at http://nacl.cr.yp.to/

**Comment by warner** [comment]
how about `nacl.raw`?

I'm agreeing with @dstufft that we should land this before the 0.3.0 release.

**Comment by alex** [comment]
`nacl.bindings` would be consistent with what pyca/cryptography does. (This
is going to be my only time weighing in, whoever implements this bikeshed
can paint it)

On Tue, Mar 3, 2015 at 7:01 PM, Brian Warner <notifications@github.com>
wrote:

> how about nacl.raw?
>
> I'm agreeing with @dstufft <https://github.com/dstufft> that we should
> land this before the 0.3.0 release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/pynacl/issues/110#issuecomment-77088743>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by warner** [comment]
righto, PR in a few minutes

**Comment by warner** [comment]
that fixes it
