### ISSUE TITLE
Freezing an app using pynacl

### ISSUE THREAD

**Issue by Insoleet** [pyca/pynacl#116]
Hello,

I'm tring to freeze my app. It's using pynacl.

I added "nacl" as a package, but when I try to launch it, it asks cffi to build the code and I get : 
distutils.errors.DistutilsPlatformError: invalid Python installation: unable to open /include/python3.4m/pyconfig.h (No such file or directory)

Is it possible to prebuilt nacl so that it an be included in the freeze package ?

**Comment by hoffmabc** [comment]
What are you using to freeze your app?

**Comment by jamiesonbecker** [comment]
(I had a similar issue using cython.)

**Comment by reaperhulk** [comment]
Closing this due to age -- in general it should be possible to do this these days.
