### ISSUE TITLE
use libsodium tarball, instead of unpacked files

### ISSUE THREAD

**Issue by warner** [pyca/pynacl#123]
This will make upgrading to new versions of libsodium (e.g. #120 / #121) easier in the future.

**Comment by dstufft** [comment]
There was a reason I did this that I can't remember why now..., it probably wasn't important if I didn't document it in the ``setup.py`` though.

**Comment by warner** [comment]
I imagine it'll make `setup.py` annoying and unpredictable, with something like:

```python
if not os.path.isdir("src/libsodium"):
    extract_tarball()
    rename()
```

that must run before `setup()` gets control. So merely running `setup.py --version` will cause side-effects.

**Comment by dstufft** [comment]
Oh hey, I noticed https://github.com/pyca/pynacl/issues/49, so I must have wanted it at some point.

You would probably just do that inside of the ``build_clib`` command instead of at the module scope in ``setup.py``. That would delay the unpacking until it actually needs to build it.

**Comment by warner** [comment]
doh, I didn't notice that one. Closing this ticket as a dup of #49.
