### ISSUE TITLE
finishing off 0.3.0 release

### ISSUE THREAD

**Issue by warner** [pyca/pynacl#131]
* send announcement to pyca mailing list
* update http://pynacl.readthedocs.org/en/latest/ ?

@dstufft where is that mailing list? And how does readthedocs.org get updated?

**Comment by dstufft** [comment]
The mailing list is https://mail.python.org/mailman/listinfo/cryptography-dev.

I thought that the docs were updating automatically, but maybe that broke when I moved PyNaCl to PyCA instead of my own personal account. I can take a look tomorrow.

**Comment by warner** [comment]
Thanks. I can't actually tell what readthedocs is using.. I don't see a git hash anywhere. But the version box thingy in the lower left corner offers "latest" and "v0.1.0", which isn't encouraging.

**Comment by dstufft** [comment]
Docs should be updated now, do you have a RTD username @warner ? I can add you to RTD.

**Comment by warner** [comment]
Just added one, "warner". Thanks.

Mail is sent, although I haven't seen it delivered yet.. might be stuck in a moderator queue?

**Comment by warner** [comment]
Ah, there it is. Ok, I think we're done here.
