### ISSUE TITLE
Decrypting short data gives 'ValueError: The nonce must be exactly 24 bytes long'

### ISSUE THREAD

**Issue by realcr** [pyca/pynacl#133]
Hi,
I'm giving box.decrypt() random data, and I expect that with high probability I will get CryptoError. (Because the ciphertext should contain an authenticator, and it should be hard to generate a valid ciphertext).

When using box.decrypt() for short random data, I get ValueError. (Which I think is a wrong behaviour). If I use it for longer random data, I get CryptoError (Which I consider to be the correct expected behaviour).

I include here my ipython transcript that shows how to reproduce this behaviour.
I'm using python 3.4 on Ubuntu 14.04 over PC, if it matters.

``` python
In [28]: import nacl.secret

In [29]: import nacl.utils

In [30]: key = nacl.utils.random(nacl.secret.SecretBox.KEY_SIZE)

In [31]: box = nacl.secret.SecretBox(key)

In [32]: message = b'This is the plaintext'

In [33]: nonce = nacl.utils.random(nacl.secret.SecretBox.NONCE_SIZE)

In [34]: encrypted = box.encrypt(message,nonce)

In [35]: plaintext = box.decrypt(encrypted)

In [36]: plaintext
Out[36]: b'This is the plaintext'

In [37]: box.decrypt(b'Short')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-37-3326120b0dc5> in <module>()
----> 1 box.decrypt(b'Short')

/home/real/.virtualenvs/mep_backend/lib/python3.4/site-packages/nacl/secret.py in decrypt(self, ciphertext, nonce, encoder)
    113         if len(nonce) != self.NONCE_SIZE:
    114             raise ValueError(
--> 115                 "The nonce must be exactly %s bytes long" % self.NONCE_SIZE,
    116             )
    117 

ValueError: The nonce must be exactly 24 bytes long

In [38]: box.decrypt(b'This is some longer data')
---------------------------------------------------------------------------
CryptoError                               Traceback (most recent call last)
<ipython-input-38-f837d208f3d7> in <module>()
----> 1 box.decrypt(b'This is some longer data')

/home/real/.virtualenvs/mep_backend/lib/python3.4/site-packages/nacl/secret.py in decrypt(self, ciphertext, nonce, encoder)
    117 
    118         plaintext = nacl.bindings.crypto_secretbox_open(ciphertext,
--> 119                                                         nonce, self._key)
    120 
    121         return plaintext

/home/real/.virtualenvs/mep_backend/lib/python3.4/site-packages/nacl/bindings/crypto_secretbox.py in crypto_secretbox_open(ciphertext, nonce, key)
     72     if lib.crypto_secretbox_open(
     73             plaintext, padded, len(padded), nonce, key) != 0:
---> 74         raise CryptoError("Decryption failed. Ciphertext failed verification")
     75 
     76     plaintext = lib.ffi.buffer(plaintext, len(padded))

CryptoError: Decryption failed. Ciphertext failed verification
```

**Comment by warner** [comment]
The input to `decrypt()` is expected to include the 24-byte nonce, so random (short) data will be too short to provide it. The code that slices off the nonce should probably be changed to report a better error message when there isn't enough nonce+ciphertext to contain the nonce, like "decrypt() was given a nonce+ciphertext that isn't big enough to contain a nonce".

I'm not positive that it should be a CryptoError though. Consider a program which had a bug that was delivering an empty string (or other short message) to `decrypt()`. If that caused a CryptoError, would you think to check the length of the encrypted message? If I were debugging that, I bet I'd spend some time checking to see if I was giving it the right key, and other crypto-ish problems, before looking for something as basic as the input being completely broken. ValueError could mean "completely broken" and CryptoError could mean "subtle corruption".

I dunno though. I could be swayed the other way too :).

**Comment by dstufft** [comment]
You don’t have to concat the nonce, you can also pass it in explicitly as the second parameter, but yes what Brian said here. I also think a ValueError makes sense here, you’re passing the right type but the value isn’t correct.

Honestly a CryptoError could probably be a subclass of a ValueError since it’s really just a specialized form of that. In any case, I think maintaining the property that a CryptoError comes from errors within sodium is a good property to maintain.

**Comment by realcr** [comment]
Hey, thanks for the response to my issue.
The way I see it, as PyNaCl symmetric encryption provides authenticity, if a byte stream can not be decrypted it means a crypto error, because somebody might have changed the data before it got to me. 

My use case is as follows: I have one server that generates tickets to clients. Those tickets are just encrypted blobs, using PyNaCl Symmetric encryption. There is another host that takes tickets from clients. The two hosts share a secret which is the encryption key. The authenticity of the tickets is verified by trying to decrypt the tickets. On the host the verifies tickets I did something like:

```python
try:
    # Decrypt and return plaintext:
    return box.decrypt(ciphertext)
except (nacl.exceptions.CryptoError):
    # Invalid ticket
    ...
```
One of my tests showed me that this is not enough (I got ValueError for short ciphertexts), and I changed the 'except' line to:
```python
except (ValueError, nacl.exceptions.CryptoError):
```

My problem with the ValueError exception that I got is that it suddenly exposes me to the structure of the ciphertext (The nonce padding), which, as the end user, I think I shouldn't care about.

That said, the current behaviour might have some other advantages that I miss. I'm still new to this library. Having one of the exceptions subclass the other is probably a good idea, as I will be able to wait for just one kind of exception, instead of two.

**Comment by lmctv** [comment]
@realcr since release 1.1, we define and use CryptoError subclasses for all raised exceptions; if I've correctly understood your desire, putting just CryptoError in the except: clause should now do what you expected.

**Comment by realcr** [comment]
Thank you for solving this!

real.
