### ISSUE TITLE
Add __eq__() magic method to key classes

### ISSUE THREAD

**Issue by codethief** [pyca/pynacl#134]
I'm using public keys as identifiers and need a way to check two such identifiers for equality. Now, the way the keys are stored internally by PyNaCl varies among the different key classes (`nacl.public.PublicKey`, `nacl.public.VerifyKey`, `nacl.public.SigningKey`, …) and I really don't want to rely on that. Hence, a magic method `__eq__()` would be a great thing to have.

I will probably add it myself in the coming days and create a pull request. Just wanted to write it down in the meantime.

**Comment by codethief** [comment]
Here we go: #135

**Comment by alexwlchan** [comment]
I think this is fixed by #232.
