### ISSUE TITLE
"python setup.py install" breaks the sources

### ISSUE THREAD

**Issue by l29ah** [pyca/pynacl#145]
So it can't be reran, resulting in an error:

running install
running build
running build_py
running build_clib
error: [Errno 17] File exists: '/tmp/pynacl/build/temp.linux-x86_64-2.7'

**Comment by reaperhulk** [comment]
This doesn't appear to be an issue any more, possibly due to setuptools changes or other changes to pynacl? At the very least I can't replicate it on my mac. Closing for now.
