### ISSUE TITLE
'Read the docs' doesn't explain how to import public keys.

### ISSUE THREAD

**Issue by maqp** [pyca/pynacl#150]
The documentation generates both key pair objects in the same program. 

    skbob = PrivateKey.generate()
    pkbob = skbob.public_key
    skalice = PrivateKey.generate()
    pkalice = skalice.public_key

Once public key has been generated, the documentation says

    # the public key can be given to anyone wishing to send Bob an encrypted message

There is however no documentation about how to I could import public key of Alice into Bob's client. I succeeded in this by doing

    bobPrivateKey = PrivateKey.generate()
    bobPublicKey = bobPrivateKey.public_key

    alicePrivateKey = PrivateKey.generate()
    alicePublicKey = alicePrivateKey.public_key
    alicePublicKey.__init__(getPublicKey())

    box = Box(bobPrivateKey, alicePublicKey)

but I'm not sure whether creating the temporary object is the correct way. Could you advice on how public key is supposed to be imported?

Thank You.

**Comment by sinner-** [comment]
Hello there, 

You should use the available encoder functions when transporting any key.

e.g.

```
In [1]: import nacl.utils

In [2]: import nacl.public

In [3]: alice_private_key = nacl.public.PrivateKey.generate()

In [4]: alice_private_key.public_key.encode
Out[4]: <bound method PublicKey.encode of <nacl.public.PublicKey object at 0x7f001b392310>>

In [5]: alice_private_key.public_key
Out[5]: <nacl.public.PublicKey at 0x7f001b392310>

In [6]: alice_private_key.public_key.encode(encoder = nacl.encoding.HexEncoder)
Out[6]: '4044f36a17ead9d784f6cab1f752a0440823f974d7757f61b9b2f8fda623d01a'

In [7]: encoded_public_key = alice_private_key.public_key.encode(encoder = nacl.encoding.HexEncoder)

In [8]: try:
   ...:     decoded_public_key = nacl.public.PublicKey(encoded_public_key, encoder = nacl.encoding.HexEncoder)
   ...: except TypeError:
   ...:     print "Error"
   ...: 

In [9]: decoded_public_key
Out[9]: <nacl.public.PublicKey at 0x7f001b392690>
```

**Comment by maqp** [comment]
I got it working with this. Thanks!
