### ISSUE TITLE
progress indicator

### ISSUE THREAD

**Issue by ac225519** [pyca/pynacl#175]
Hello,

I'm wondering is there any way to get a progress indicator for the  nacl.signing.SigningKey.generate()
function ?
I'm willing to do also a patch of libsodium if necessary to get a progress indication.

**Comment by reaperhulk** [comment]
Generation of a key using that function should take very little time. Benchmarking it on my system I consistently get a key in between 1 and 3 milliseconds. What use case requires a progress indicator for an operation that quick?

**Comment by ac225519** [comment]
It is used that way:
`
static char * createGUID()
{
  sodium_init();

  unsigned char out[crypto_hash_sha512_BYTES];
  unsigned char sk[crypto_sign_SECRETKEYBYTES];
  int valid_pow = 0;
  while (valid_pow == 0){

    //Generate a key pair
    unsigned char pk[crypto_sign_PUBLICKEYBYTES];
    unsigned char sk[crypto_sign_SECRETKEYBYTES];
    crypto_sign_keypair(pk, sk);

    //Hash the pubkey with sha512
    crypto_hash_sha512(out, pk, crypto_sign_PUBLICKEYBYTES);
    char proof_of_work[44];
    memcpy(proof_of_work, &out[20], 44);
    char * pow = to_hex(proof_of_work, 3);
    valid_pow = test_pow(pow);
  }
  to_hex(sk, 32);
  return to_hex(sk, 32);
}
`
And it takes 30 sec. to 60 min. depending on hardware.
On my hardware about 3 minutes.
Without any kind of progress initiator or at least alive sign.

**Comment by reaperhulk** [comment]
That is...baffling. For reference:

```
time python -c "import nacl.signing;nacl.signing.SigningKey.generate()"

real	0m0.061s
user	0m0.041s
sys	0m0.012s
```

Even on a raspberry pi I would expect this to be reasonably fast...

**Comment by alex** [comment]
Your function does a ton of stuff, not just generate a key in the same way `SigningKey.generate()` does (your function isn't even in Python, so I'm pretty confused)

**Comment by alex** [comment]
(Unless there's more details on what the pynacl bug is and how to reproduce, I'm going to close this)
