### ISSUE TITLE
expose BLAKE2

### ISSUE THREAD

**Issue by zooko** [pyca/pynacl#178]
Dear pynacl developers:

Thank you very much for this library!

I request that pynacl expose the "generic hash" function from
libsodium (https://download.libsodium.org/doc/hashing/generic_hashing.html).
This is, of course, BLAKE2!

Reasons:
- It's safer than SHA-256 or SHA-512, because it is invulnerable to
  length-extension.
- It is descended from and closely related to BLAKE, which got higher
  marks than even Keccak got in the SHA-3 contest (please see
  https://blake2.net/acns/slides.html ).
- It is descended from and closely related to Salsa20 and ChaCha20,
  which have gotten much scrutiny and passed with flying colors.
- It is much more efficient than SHA-256 or SHA-512 for most platforms and uses.
- It is what the authors of libsodium thought should be the default
  hash function for users who didn't have a reason to choose a different
  hash function.
- An implementation of it is already shipping inside pynacl, and has
  been all along, it just isn't exposed in the API.
- It's what the hip modern applied cryptographer reaches for when they
  need a secure hash function (e.g. the Password Hashing Competition
  entrants on https://blake2.net/#us).
- It is currently being added to Bouncy Castle, Crypto++, and OpenSSL.
  You don't want to be the last kid on your block to support BLAKE2 do
  you !?
- https://github.com/saltstack/libnacl and https://pypi.python.org/pypi/pysodium already expose BLAKE2 a.k.a. "generic hash".

**Comment by alex** [comment]
@zooko Do you want both keyed and unkeyed? Also do you have opinions about a single-shot API or streaming?

**Comment by zooko** [comment]
Both keyed and unkeyed seem useful, yes. No opinion about single-shot vs. streaming APIs.

**Comment by alex** [comment]
Oh, I should have asked, `b` vs. `s`?

**Comment by zookozcash** [comment]
Well, the "generic hashing" in libsodium is BLAKE2b:
https://download.libsodium.org/doc/hashing/generic_hashing.html

BLAKE2b is the default recommended by the BLAKE2 authors because it is
faster on 64-bit CPUs (for long inputs — longer than 64 bytes):

http://bench.cr.yp.to/results-hash.html

Now, I would *also* advocate adding BLAKE2s, since it is faster on 32-bit
CPUs and it is faster (even on 64-bit CPUs) for short inputs, and it uses
less RAM.

**Comment by alex** [comment]
@zooko Are there any official vectors for the unkeyed blake2 variant? The ones in the repo ATM are keyed only.

**Comment by zooko** [comment]
I asked Samuel Neves, who replied saying:

The KATs in https://
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2-kat.h>github.com
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2-kat.h>/
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2-kat.h>BLAKE2
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2-kat.h>/
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2-kat.h>BLAKE2
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2-kat.h>
/blob/master/ref/
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2-kat.h>blake2-kat.h
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2-kat.h> include
results with and without keying. See
https://
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2b-ref.c#L377-L406>
github.com
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2b-ref.c#L377-L406>/
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2b-ref.c#L377-L406>
BLAKE2
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2b-ref.c#L377-L406>/
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2b-ref.c#L377-L406>
BLAKE2
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2b-ref.c#L377-L406>
/blob/master/ref/
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2b-ref.c#L377-L406>
blake2b-ref.c#L377-L406
<https://github.com/BLAKE2/BLAKE2/blob/master/ref/blake2b-ref.c#L377-L406> for
how to verify them, replacing
blake2x_keyed_kat by blake2x_kat.

**Comment by lmctv** [comment]
@zooko would you mind taking a look at my attempt at an implemetation in the add-generichash branch  of lmctv/pynacl@ba59a7994e28ab1ae54206ec7d46ddc235113d6f ?

I tried to implement both the streaming API and the one-shot one; if you can spare some moments, I'd be grateful for any comment. Thank you

**Comment by zookozcash** [comment]
https://github.com/lmctv/pynacl/commit/ba59a7994e28ab1ae54206ec7d46ddc235113d6f

**Comment by lmctv** [comment]
@zooko would you mind taking a look at my open PRs #216 and #217 ?

**Comment by maqp** [comment]
@zooko [Python3.6's hashlib now comes with BLAKE2](https://docs.python.org/3/library/hashlib-blake2.html#module-hashlib).

**Comment by reaperhulk** [comment]
Done in #215, #216, #217 and will be released in 1.1.0
