### ISSUE TITLE
Secret box not packing correctly?

### ISSUE THREAD

**Issue by izy521** [pyca/pynacl#181]
Hello! I'm a user of the [TweetNacl](https://github.com/dchest/tweetnacl-js) library for my Node.js application. I specifically use their SecretBox (Secret Key) to handle encrypting messages to and from a certain API. I tried doing this using your library under Python, but the output data here seems to be a bit different.

For example, the first 12 bytes of data from the encrypted box in this library are: 
```
[128, 120, 0, 1, 0, 0, 0, 0, 0, 0, 0, 16]
```
which seem to be the first 12 bytes from our (constantly changing) predefined nonce.

But the first 12 bytes from the same data, using the Node library are:
```
[ 195, 54, 218, 210, 95, 173, 240, 201, 64, 208, 13, 229 ]
```
The Node data varies because of the encryption, but the Python data stays the same every time. Am I doing something incorrect? I've followed the SecretBox instructions down to the letter, but I don't think it should be prepending the nonce.

**Comment by izy521** [comment]
Not sure why I didn't think of this earlier, but stripping the nonce from the return gave me what I needed. I think it should be worth mentioning somewhere that the nonce prepends the data.

**Comment by dstufft** [comment]
Just for the record, the secret box ``encrypt()`` function doesn't actually return bytes it actually returns a class called ``EncryptedMessage``. This is documented [here](https://pynacl.readthedocs.org/en/latest/utils/#EncryptedMessage), but basically it's a bytes object that has nonce prepended to the ciphertext, but it also has a ``.nonce`` and ``.ciphertext`` attribute to allow accessing either one independently.

**Comment by izy521** [comment]
Ah, so it was a case of me overlooking something, thanks.
