### ISSUE TITLE
expose crypto_box_seal() and crypto_box_seal_open()

### ISSUE THREAD

**Issue by iambrosie** [pyca/pynacl#182]
Hi guys,

Would it be possible to explose libsodium's crypto_box_seal() and crypto_box_seal_open()?
As discussed here: https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes.html, they allow for some interesting use cases.

Thanks!

**Comment by ztane** [comment]
Not only that, but the problem with using the standard public key boxes is that if the sender key is compromised later on, then the message can also be recovered; and to use ephemeral keys, one has to decide an encoding scheme to ship the public key along.

**Comment by reaperhulk** [comment]
I have no objection to their addition, so if someone wants to step up and contribute a PR that'd be great!

**Comment by mitra42** [comment]
Sorry, i'm not familiar enough with the code (libsodium,  pynacl or the care needed to avoid inadvertent insecurity) to do that

**Comment by lmctv** [comment]
@reaperhulk I'm volunteering, but I'd like to avoid juggling with too many PRs in flight (hint, hint...)

**Comment by lmctv** [comment]
While I'll be going through the cffi route, this could also be implemented just composing the already present cffi bindings for  crypto_box_keypair(), crypto_box() and crypto_box_open(); what about adding an example of such a composition to the docs?

**Comment by lmctv** [comment]
I've just started implementing the SealedBox high-level API; the preliminary branch is named "add-crypto-box-seal-apis" at lmctv/pynacl

I'd be grateful for any preliminary review, before I start adding the needed tests.

**Comment by lmctv** [comment]
@mitra42 while I can understand your frustration, the Box API is just a well-implemented DH key agreement, which imply both parties need the other's public key to be able to generate the shared key.

**Comment by mitra42** [comment]
Well this is another case of the PyNaCl bindings supporting different subsets of libsodium than the Javascript bindings, making it really really hard to write cross-platform applications.  There are good applications for the Sealed box, (just knowing private key of recipient) which is why I presume it was in libsodium. Yes you can do nasty workarounds specific to PyNaCl (e.g. shipping the public key along with the data) but it seems a pity to make specific workarounds when the underlying C code is already there to do this.

**Comment by lmctv** [comment]
@mitra42 while I concur with your desire to avoid creating new half-baked constructs, the sealed_box one being so straightforward, I think a reimplementation in terms of existing APIs wouldn't take more than another dozen lines, and I'm thinking about doing that just for the sake of tests.

I'd be really grateful if you could spare some time and take a look at my preliminary pull request and let me know if the APIs I'm proposing make sense to you. Thank you very much.

**Comment by lmctv** [comment]
@iambrosie @ztane would you mind taking a look to the preliminary pull request I've put at lmctv/pynacl#4 and let me know whether it seems useful in solving your problems, or if you think there's something missing?

**Comment by mitra42** [comment]
Thanks - that looks correct to me.

**Comment by lmctv** [comment]
@mitra42 I've just saved a reimplementation of Secret is as a gist at https://gist.github.com/lmctv/d76a2ebefd3227c461ff5450ea487a11

@reaperhulk I think both this and from_seed could be useful as executable documentation, or as a guide for those stuck on a previous version, but I'm unsure if there is a place fit for them in the source tree.

**Comment by lmctv** [comment]
@iambrosie while you still need to manually build from git, we expose both the low level bindings and an high level SealedBox class. IMHO, the issue can be closed.
