### ISSUE TITLE
Fallback to "bundled" when not both libsodium and headers are there

### ISSUE THREAD

**Issue by oberstet** [pyca/pynacl#184]
Currently, PyNaCl will check for availability of system libsodium, but it does not check for development headers. And then fails to build.

It would be nice if it would check for both system libsodium _and_ headers, and not both are available, automatically fall back to a "bundled" build.

> This was discussed on IRC .. @dstufft

**Comment by warner** [comment]
We hit this in magic-wormhole too: https://github.com/warner/magic-wormhole/pull/10

I was able to reproduce it on an ubuntu-15.10 VM in which `libsodium13` was installed, but `libsodium-dev` was not. This would be the case if you've apt-get installed some other package that needs libsodium (like `dnscrypt-proxy`), or if you've previously installed a .deb of `python-nacl` but then uninstalled it, leaving `libsodium13` behind.

I think the immediate problem is that the glue code is built (with cffi) from a `#include <sodium.h>` line, which obviously needs headers from *somewhere*. Would it make sense to use the bundled header files, even if we're using a system-supplied `libsodium.so`?

Failing that, maybe setup.py's `use_system()` should do a trial compile of some sort (just a trivial `#include`) and if that fails, return False to use the bundled option.

Or, as #185 suggests, make bundled the default and only use the system library if explicitly asked for it by an environment variable (removing the FFI test from `use_system()` entirely).

**Comment by reaperhulk** [comment]
We can also improve this situation by shipping a `manylinux1` wheel. I've got the go ahead on doing it for cffi and I'm planning to ship a `bcrypt` wheel soon to test the waters. If all goes well a pynacl wheel could follow soon after :)

That will only fix it for people on x86/x86_64 on linux with the latest pip though, so I'd definitely be in favor of swapping to make bundled the default behavior.

**Comment by AraHaan** [comment]
Same thing happens on Windows since Windows does not come with a system wide libsodium then build fails. (Python 3.6 alpha 3 currently)
