### ISSUE TITLE
Make "bundled" the default

### ISSUE THREAD

**Issue by oberstet** [pyca/pynacl#185]
Currently, PyNaCl will be default look for a system libsodium, and to use the bundled lib, one needs to have an environment variable `SODIUM_INSTALL=bundled` set.

This is IMO not the best, because:
1. it is not possible to set environment variables from wheel based installs (when X depends on PyNaCl, and X is a universal wheel, then X cannot be installed easily forcing bundled)
2. System libsodium is often outdated. This is a potential security issue. Also, I'd expect the bundled libsodium to be more thoroughly tested/compatible with the bundled libsodium rather than any system one)

Hence, I would like to propose making "bundled" the default, and only override that via `SODIUM_INSTALL=system`.

> This was discussed on IRC .. @dstufft

**Comment by reaperhulk** [comment]
This is done (it will be in 1.1.0)
