### ISSUE TITLE
document seems wrong.

### ISSUE THREAD

**Issue by steverweber** [pyca/pynacl#189]
https://github.com/pyca/pynacl/blob/master/docs/public.rst

> But once the padlock snaps shut, the box cannot be opened by anyone who doesn't have Alice's private key...

it seems that bob is a lock smith because he had no issue reading the contents after encryption?

```
import nacl.utils
from nacl.public import PrivateKey, Box
skbob = PrivateKey.generate()
pkbob = skbob.public_key
skalice = PrivateKey.generate()
pkalice = skalice.public_key
bob_box = Box(skbob, pkalice)
message = b"Kill all humans"
nonce = nacl.utils.random(Box.NONCE_SIZE)
encrypted = bob_box.encrypt(message, nonce)

alice_box = Box(skalice, pkbob)
plaintext = alice_box.decrypt(encrypted)

print(bob_box.decrypt(encrypted))
# "Kill all humans"
```

is there a way to do one way encryption using nacl?

**Comment by dstufft** [comment]
> is there a way to do one way encryption using nacl?

No. That's because NaCL public key encryption is actually combining the public/private key to come up with a shared secret, and then using that shared secret as an input to a symmetric cipher. It's not actually public/private key encryption in the traditional, RSA sense.

**Comment by steverweber** [comment]
one way encryption like...

nacl.enc('raw_data', public_key)
nacl.dec('enc_data', private)

nacl.dec('enc_data', public_key) ... fails

**Comment by dstufft** [comment]
Ah- I'm actually (sort of) wrong, there is [Sealed Boxes](https://download.libsodium.org/libsodium/content/public-key_cryptography/sealed_boxes.html) in libsodium now which is sort of that. It's really the same thing under the covers, two key pairs generate a shared secret for a symmetric cipher, but it has baked into it the idea that the sender side is using an emphereal key that gets thrown away after one encryption operation, which means the sender never gets access to their side of the equation so they can't then decrypt it later.

**Comment by steverweber** [comment]
ah cool! thanks.

**Comment by dstufft** [comment]
Note: I don't know if this primitive is exposed in PyNaCl yet, though I'm sure a PR to add it would be accepted. Of course you could implement the same idea using ``Box`` just be making your own emphereal keys for it.

**Comment by steverweber** [comment]
https://download.libsodium.org/libsodium/content/public-key_cryptography/sealed_boxes.html

humm i don't really get how to do the emphereal key

```
import nacl.utils
from nacl.public import PrivateKey, Box

skalice = PrivateKey.generate()
pkalice = skalice.public_key

skanonymous = PrivateKey.generate()
pkanonymous = skanonymous.public_key

anonymous_box = Box(skanonymous, pkalice)

nonce = nacl.utils.random(Box.NONCE_SIZE)

encrypted = bob_box.encrypt(b"Kill all humans", nonce)

alice_box = Box(skalice, None?)
alice_box.decrypt(encrypted)
```
