### ISSUE TITLE
Warning from import nacl.signing

### ISSUE THREAD

**Issue by robehickman** [pyca/pynacl#190]
Importing nacl.signing outputs the following notice in the terminal.

/usr/local/lib/python2.7/dist-packages/cffi-1.6.0-py2.7-linux-x86_64.egg/cffi/vengine_cpy.py:191: UserWarning: reimporting '_cffi__xaae2f857x60f2fbbc' might overwrite older definitions
  % (self.verifier.get_module_name()))

**Comment by reaperhulk** [comment]
This shouldn't happen with more recent pynacl releases (1.0+)
