### ISSUE TITLE
Storing or transmitting public keys

### ISSUE THREAD

**Issue by libeclipse** [pyca/pynacl#192]
There should be a way to convert the public_key into a storable or transmittable item. For example PEM encoding or similar. Currently when trying to serialise the public_key into a JSON object is not possible. Storing the keys isn't possible either. The only possible solution I've come across is using pickle to serialise the object, but this isn't a clean solution.

Is there anything else?

**Comment by libeclipse** [comment]
An example would be pycrypto which has the exportKey() and importKey() functions.

**Comment by reaperhulk** [comment]
You can seralize the key using the `encode` facilities pynacl exposes: http://pynacl.readthedocs.io/en/latest/encoding/

For example:
```
import nacl
from nacl.public import PrivateKey, PublicKey


key = PrivateKey.generate()
encoded_public_key = key.public_key.encode(encoder=nacl.encoding.Base64Encoder)
loaded_public_key = PublicKey(encoded_public_key, encoder=nacl.encoding.Base64Encoder)
assert loaded_public_key.encode() == key.public_key.encode()
```

The `encoded_public_key` is just a base64 encoding of the byte representation of the key.

**Comment by webjunkie** [comment]
You might use the cryptography library which has support for the key type nacl is using.
As far as I can see, this works, but without guarantee that it's the right PEM and compatible where expected...

```python
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import Encoding, PrivateFormat, NoEncryption
from nacl.public import PrivateKey

key = PrivateKey.generate()
cryptography_key = Ed25519PrivateKey.from_private_bytes(bytes(key))
cryptography_key.private_bytes(
    encoding=Encoding.PEM, format=PrivateFormat.PKCS8, encryption_algorithm=NoEncryption()
)
```

**Comment by reaperhulk** [comment]
pynacl doesn't use PKCS8 encoding for its keys. If you want to export ed25519 private keys from cryptography and import them to pynacl you'll need to do:
```
cryptography_key.private_bytes(
    encoding=Encoding.Raw, format=PrivateFormat.Raw, encryption_algorithm=NoEncryption()
)
```
