### ISSUE TITLE
Random Nonces by Default?

### ISSUE THREAD

**Issue by dstufft** [pyca/pynacl#21]
There are a number of places where the api expects a nonce. Ideally a nonce should never be reused. However DJB has stated for both Symmetrical and Asymmetrical encryption that with a random nonce the collision risk is negligible[1][2].

Currently PyNaCl documentation has lots of warnings but given with the "Crypto without the sharp edges" ideal should PyNaCl by default generate a random nonce? This will need a resolution to https://github.com/dstufft/pynacl/issues/20 or will need to change the `encrypt()` function to return a tuple of `(nonce, ciphertext)`.

[1] http://nacl.cr.yp.to/box.html
[2] http://nacl.cr.yp.to/secretbox.html

**Comment by warner** [comment]
Oh, while writing one app, I found it'd be handy to provide the nonce as an integer (encrypting multiple segments of a large file, holding only one segment in memory at a time, using the nonce as the segment number). So maybe have `encrypt()` accept a `nonce_int=` kwarg too (and obviously it's an error to pass both `nonce=` and `nonce_int=`). This would imply a particular encoding for the integer (little-endian vs big-endian) that isn't present in nacl itself. Does libsodium provide/endorse anything here?

I also thought it'd be useful to provide a utility function that would extract the nonce from a boxed or secretboxed message, and maybe a second one that turns it back into an integer. This would be handy for protocols that are rejecting duplicate/old/out-of-order messages: check the nonce before decrypting anything. I can't decide if this function should be an attribute of the key objects, or if they should be non-method functions in `public.py`/`secret.py`.. I guess I lean towards the latter.

**Comment by lvh** [comment]
I didn't find anything endorsed while writing caesium, but went with big-endian: https://github.com/lvh/caesium/blob/master/src/caesium/crypto/secretbox.clj#L29-L42

**Comment by reaperhulk** [comment]
This is done (it will be in 1.1.0). See #210

**Comment by lvh** [comment]
This is fantastic and one of the best UX improvements I've seen in cryptographic software in a long time. Fantastic job @reaperhulk :)
