### ISSUE TITLE
Python 3 CI

### ISSUE THREAD

**Issue by ofek** [pyca/pynacl#246]
Is it known our Travis setup only tests py2?

**Comment by reaperhulk** [comment]
It doesn't only test py2. Look at the install scripts.

**Comment by lmctv** [comment]
Just to add my cent to reaperhulk's reply: you can just look at some running build job:
https://travis-ci.org/pyca/pynacl/builds/196251529

**Comment by ofek** [comment]
Sorry, codecov was just being finicky for #245.
