### ISSUE TITLE
Document new functionality in /docs

### ISSUE THREAD

**Issue by reaperhulk** [pyca/pynacl#248]
https://pynacl.readthedocs.io/en/latest/ is built from the docs dir. Unfortunately we don't have docs for the `nacl.hashlib` module, `scrypt` in general, and the output for [blake2b](https://pynacl.readthedocs.io/en/latest/api/hash/) is not parsing properly. We need to get this fixed up before we can do a 1.1.0 release (docs can be built and viewed locally using `tox -e docs` and then looking at `docs/_build/html/index.html`

**Comment by reaperhulk** [comment]
#239 partially addresses this (scrypt)

**Comment by lmctv** [comment]
I'm beginning to write a nacl.hashlib API doc.

**Comment by lmctv** [comment]
I think most of the new stuff is documented now

**Comment by reaperhulk** [comment]
I think I agree. Anything additional missing we'll just open PRs directly for.
