### ISSUE TITLE
New release requested

### ISSUE THREAD

**Issue by lispyclouds** [pyca/pynacl#265]
This is regarding #199 

Can a new release be made having this fix soon? The Debian package matrix-synapse depends on this and the last released version(1.0.1) is causing issues regarding the init_once.

**Comment by reaperhulk** [comment]
I'll be looking at this after the pyca/cryptography release. #253 is really the only blocker for 1.1.0 and we should be able to sort that out.

**Comment by lispyclouds** [comment]
Thank you!

**Comment by reaperhulk** [comment]
Done!
