### ISSUE TITLE
Expose / move into XChaCha20?

### ISSUE THREAD

**Issue by maqp** [pyca/pynacl#267]
[The latest version of libsodium has implemented XChaCha20](https://github.com/jedisct1/libsodium/releases/tag/1.0.12). While there's nothing that would indicate a problem in XSalsa20, improved diffusion should make XChaCha20 more secure. IIRC pynacl does it's best to avoid giving users too many choices. The library is most likely already widely deployed, but I'd imagine not so widely it's too late to make the change. Personally I think minimizing the code base is worth the inconvenience for developers and users, but if backwards compatibility is desired, maybe it's OK as there would be no choice developers can go wrong with.

**Comment by jedisct1** [comment]
If you need an AEAD construction, XChaCha20 is a good option, especially as other libraries may implement the exact same construction.

As a replacement for `crypto_box` and `crypto_secretbox`, it's virtually useless. ChaCha20 is not more secure.

It has faster diffusion, but it doesn't make any practical difference after the first few rounds. Their security margins are similar. And if a major attack is found against Salsa, ChaCha is likely to be equally affected, as well as many constructions based on the same design.

ChaCha20 is not faster either. With the libsodium AVX2 implementations, their speed is comparable.

**Comment by maqp** [comment]
That's great to hear. (Personally I don't need AEAD as I'm doing authenticated encryption over any headers that contain sensitive headers/data. 

I'm leaving the issue open until the maintainers agree on whether additional/alternative implementation that also provides AEAD is needed.

**Comment by maqp** [comment]
Closing this to make way for #308.
