### ISSUE TITLE
`import nacl.utils` get error

### ISSUE THREAD

**Issue by inflation** [pyca/pynacl#272]
If I run 
```python
import nacl.utils
```
at beginning, it will output
```
ImportError: cannot import name 'ensure'
```

After importing any other pynacl module, the error disappear.

**Comment by reaperhulk** [comment]
Thanks for the report. Confirmed it's occurring for me too. @lmctv do you have time to take a quick look here?

**Comment by lmctv** [comment]
The problem stems from a circular import nacl.utils needs nacl.bindings for random which needs nacl.utils for ensure. Give me a couple minutes more to locally check my changes.

**Comment by lmctv** [comment]
OK, I just pushed the changes to the branch lmctv/pynacl@655070e835f5ac8957c56c9f053b78a2666ae3b7. Waiting for travis checks running at https://travis-ci.org/lmctv/pynacl/builds/211181528 before sending a pull request.

**Comment by lmctv** [comment]
@inflation would you mind double checking #273 PR? Thank you.

**Comment by inflation** [comment]
@lmctv Thanks, #273 will fix it.

**Comment by lmctv** [comment]
@inflation Can you check the just released 1.1.1 and verify if this issue can be closed?

**Comment by inflation** [comment]
@lmctv 1.1.1 fixed it. Thanks!
