### ISSUE TITLE
Tests fail on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [pyca/pynacl#286]
Tests fail with 1.1.1 and 1.1.2:
```
__________________________________________________________________________ ERROR collecting tests/test_bindings.py ___________________________________________________________________________
ImportError while importing test module '/usr/ports/security/py-pynacl/work/PyNaCl-1.1.1/tests/test_bindings.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_bindings.py:22: in <module>
    from nacl import bindings as c
E   ImportError: No module named nacl
_____________________________________________________________________________ ERROR collecting tests/test_box.py _____________________________________________________________________________
ImportError while importing test module '/usr/ports/security/py-pynacl/work/PyNaCl-1.1.1/tests/test_box.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_box.py:21: in <module>
    from nacl.encoding import HexEncoder
E   ImportError: No module named nacl.encoding
```

**Comment by yurivict** [comment]
Tests fail when the package is built but not installed. They should pass in the build directory without installing.

**Comment by lmctv** [comment]
Are you building the package directly via `python setup.py build`/`pip bdist_wheel` or is the build being driven by a script/Makefile? In the latter case, could you please post a build log?

**Comment by yurivict** [comment]
This command fails:
```
python2.7 -m pytest -rs tests
```
but this command succeeds:
```
PYTHONPATH=../stage/usr/local/lib/python2.7/site-packages python2.7 -m pytest -rs tests
```
PYTHONPATH is needed for tests.

I think, it should run tests from the local build directory without the environment variable.

For reference, py-openssl and py-oauthlib run tests with this command: ```python2 setup.py test```
There should be no need to supply PYTHONPATH.

**Comment by lmctv** [comment]
From a cursory look at https://svnweb.freebsd.org/ports/head/security/py-pynacl/Makefile?revision=436772&view=markup , I was suggesting to try and replace the
```
do-test:
	        @cd ${WRKSRC} && ${SETENV} PYTHONPATH=../src ${PYTHON_CMD} -m pytest -rs tests
```
Stanza in the Makefile with something similar to the
```
do-test:
	        @(cd ${WRKSRC} && ${PYTHON_CMD} ${PYSETUP} test)
```
that's used in py-openssl's Makefile https://svnweb.freebsd.org/ports/head/security/py-openssl/Makefile?revision=434646&view=markup&pathrev=436772

Anyways, I think the problem you are experiencing is a ports/packaging one, and therefore the freebsd maintainers of the package port should be in a better position to fix it than the upstream authors and contributors.

Thank you very much for your help towards a better pynacl.

**Comment by yurivict** [comment]
This is a minor problem anyways.
Thanks for your attention,
closing.
