### ISSUE TITLE
Batch verification features?

### ISSUE THREAD

**Issue by ccao93** [pyca/pynacl#289]
Hi,

Can we use pynacl to do Ed25519 batch verification? I can't find the implementation of batch verification in the documents.

Thank you.

**Comment by reaperhulk** [comment]
Is batch verification something libsodium supports?

**Comment by chen-dwolla** [comment]
I think it's not supported by libsodium.

**Comment by chen-dwolla** [comment]
@reaperhulk I read that in ed25519's paper and pynacl documentation, so I am wondering how to use this feature. Thank you
http://pynacl.readthedocs.io/en/latest/signing/#ed25519

**Comment by reaperhulk** [comment]
I didn't write that section of the docs but I don't believe that's a special batch verification function. Rather, it is a statement about the achievable speed due to the small code size and efficiency of the algorithm. It's also unlikely that identical performance is achievable in pynacl as you have the additional overhead of the Python runtime.

**Comment by dstufft** [comment]
Pretty sure I copy/pasted that directly from https://ed25519.cr.yp.to/

**Comment by dstufft** [comment]
FWIW if you reuse a ``pynacl.signing:SigningKey`` instance, then you should get the fastest speed capable of signing multiple items. For verification I don't think there is anything extra in libsodium besides what we're already using.

**Comment by chen-dwolla** [comment]
@reaperhulk Thank you for the explanation. That's also what I am thinking of.
@dstufft I checked lots of libraries, and none of them implemented batch verification. So I think it's still in benchmarking. You can find it in crypto_sign/ed25519 of https://bench.cr.yp.to/supercop.html
Again, thank you for your guys reply and contributions to the library.
