### ISSUE TITLE
Secret Box Decryption fails to decrypt cipher text and stops working entirely 

### ISSUE THREAD

**Issue by scglenn** [pyca/pynacl#291]
After a 10 seconds of my python script decrypting audio packets it will randomly fail to decrypt a packet and all other packets afterwards cannot be decrypted. Does the secret box need to be re-created after a failure?

EDIT: 
Is the SecretBox object safe for sharing across 2 threads?

**Comment by lmctv** [comment]
While, in general, {de,en}cryption objects should not be shared between threads, I'd like to understand how you are using SecretBox, since its intended use-case is that of single message encryption, and doesn't provide a streaming API.

**Comment by scglenn** [comment]
Sorry for the late response. I eventually fixed this issue. The problem was that sometimes a TCP packet I received was still lagging behind some bytes of data so when I decrypted the packet it would fail.
The project for this can be found here: https://github.com/scglenn/PySNAC
SecretBox was used to decrypt a stream of audio which gave very good audio quality.

**Comment by lmctv** [comment]
If I understand you correctly, and this was a caller glitch, the issue could get closed.

**Comment by lmctv** [comment]
@scglenn do you think this issue can be closed?
