### ISSUE TITLE
pip install pynacl fails with: error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hwoarang** [pyca/pynacl#298]
I am trying to install pynacl on openSUSE 42.2 but it fails with ``error: [Errno 2] No such file or directory`` during the build phase

here is some of the output

```
~> pip install pynacl                                                          
Collecting pynacl                                                                                                                                                                                                  
  Using cached PyNaCl-1.1.2.tar.gz                                                                   
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from pynacl)                     
Requirement already satisfied: cffi>=1.4.1 in ./.local/lib/python2.7/site-packages (from pynacl)                          
Requirement already satisfied: pycparser in ./.local/lib/python2.7/site-packages (from cffi>=1.4.1->pynacl)
Building wheels for collected packages: pynacl                                                           
  Running setup.py bdist_wheel for pynacl ... error                                                      
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-WNVVlf/pynacl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');
f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpCBHg6Lpip-wheel- --python-tag cp27:
  running bdist_wheel                                                                                    
  running build                                                          
  running build_py                                                                                       
  creating build                                                                                         
  creating build/lib.linux-x86_64-2.7                               
  creating build/lib.linux-x86_64-2.7/nacl 
[...]
    checking for nanosleep... yes
    checking for posix_memalign... yes
    checking for getpid... yes
    checking if gcc/ld supports -Wl,--output-def... not needed, shared libraries are disabled
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating dist-build/Makefile
    config.status: creating libsodium.pc
    config.status: creating libsodium-uninstalled.pc
    config.status: creating msvc-scripts/Makefile
    config.status: creating src/Makefile
    config.status: creating src/libsodium/Makefile
    config.status: creating src/libsodium/include/Makefile
    config.status: creating src/libsodium/include/sodium/version.h
    config.status: creating test/default/Makefile
    config.status: creating test/Makefile
    config.status: executing depfiles commands
    config.status: executing libtool commands
    error: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-WNVVlf/pynacl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-PAHH7o-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-WNVVlf/pynacl/
```

A copy of the entire log can be found here
http://artifacts.opnfv.org/cross-community-ci/openstack/bifrost/review.openstack.org/367608/8/openstack-bifrost-verify-suse-virtual-master/build_log.txt

It's not exactly clear from the output what `No such file or directory` actually means

**Comment by reaperhulk** [comment]
You need to install `make`. That's definitely an unclear error message. I had to build a tumbleweed docker image to figure it out. I suppose we could potentially detect `make` on `PATH` in setup.py.

**Comment by hwoarang** [comment]
@reaperhulk yes that fixed it. Thank you

**Comment by jamesongithub** [comment]
is make a new dep? our docker builds just started failing on this

**Comment by dstufft** [comment]
No, it's been building the libsodium library using ``make`` for years now.

**Comment by derekbekoe** [comment]
@jamesongithub @dstufft Our docker builds also started failing with this error in the last day or so.
It appears 'something' (maybe not pynacl) changed.
@jamesongithub I'd be interested to see what the common link is.
Our base image is `python:3.5.2-alpine`.

**Comment by derekbekoe** [comment]
Adding `apk add make` fixes my Alpine Docker image builds.

**Comment by rifelpet** [comment]
Also seeing recent failures in our CentOS 7 docker image build. `yum install -y make` fixed it but I'm curious what occurred recently that broke this.

**Comment by dstufft** [comment]
Dunno what changed, the latest version of PyNaCl was released like ~10 weeks ago, so if it just started failing in the last few days it would have to be something else.

**Comment by reaperhulk** [comment]
paramiko 2.2 shipped 3 days ago with pynacl as a new dep (to provide ed25519 support). That's probably it.

**Comment by jamesongithub** [comment]
makes sense, ours was pulled in via ansible which doesn't lock paramiko versions

**Comment by reaperhulk** [comment]
For users with pip 8.1+ we can simplify this by shipping a manylinux1 wheel (an item that's been on my radar for a while but I haven't gotten around to it since I've been focusing on pyca/cryptography work). I'll build and upload those wheels shortly.

**Comment by dstufft** [comment]
Note that this is possibly fully resolvable, but to do so will likely require someone motivated to write a patch with enough understanding of the C build toolchain to make it work.

Basically the history here (going off my memory!) is that I used to use distutils to build the libsodium c library, but I ended up having a problem doing that because the build process of libsodium generates some of the files as part of the ``./configure`` step (I think?). Thus I ended up just switching out using distutils to build the c library to instead use the more traditional ``./configure && make``.

So this could go back to using distutils, but someone would need to do some work to get that working. It *might* work to just first do ``./configure`` and to generate the files and then use distutils instead of ``make`` to do the compiling I don't know. It also might be possible to replicate whatever ``.c`` or ``.h`` generation that needs to get done in Python instead of using ``./configure && make``.

If someone feels like tackling this, this is the commit where I switched from just using plain old distutils to shelling out: https://github.com/pyca/pynacl/commit/adf1add13beae1d40ad5949ffcce8f735b012501.

**Comment by jamesongithub** [comment]
thanks @reaperhulk how do we know if our distro supports manylinux1

**Comment by reaperhulk** [comment]
If it's older than centos 5 or does not use glibc (alpine linux) then it is incompatible. Otherwise the manylinux1 wheels should work.

**Comment by samuraii** [comment]
If this helps to someone I got thi issue while installing dependencies with pip on Ubuntu 16. All I did was "pip install -U pip" to upgrade pip as it was very old version, and installed stuff from here https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit.
