### ISSUE TITLE
_sodium.so issue with Ubuntu 14.04 and Python 2.7.12

### ISSUE THREAD

**Issue by microwavedboy** [pyca/pynacl#301]
With the embedded version of libsodium, PyNaCl appears to be throwing exceptions with version PyNaCl 1.1.2 on Python 2.7.12

File "/usr/local/pip/nacl/bindings/crypto_box.py", line 18, in <module>
 from nacl._sodium import ffi, lib
 ImportError: /usr/local/pip/nacl/_sodium.so: undefined symbol: sodium_munlock

**Comment by reaperhulk** [comment]
By embedded do you mean the bundled copy? It may not be loading the proper underlying shared object based on that error. Do you have a system installed libsodium?

**Comment by reaperhulk** [comment]
I can't replicate this on stock Ubuntu 14.04 so it seems likely there's something specific to your system that's causing this linking issue. I just pushed up a manylinux1 wheel set though, so if you're running pip >= 8.1 try reinstalling and it should grab the wheel.

**Comment by microwavedboy** [comment]
Yes; apologies, I did mean the "bundled copy".

This appears to have addressed my issue.

I didn't have libsodium installed on my system, nor did I have another
version of PyNaCl installed in that particular directory. I attempted to
uninstall and reinstall before you added the manylinux1 wheel but to no
avail.

Thanks for the wheel and the fast response.
- A
