### ISSUE TITLE
libsodium slow build time

### ISSUE THREAD

**Issue by uSpike** [pyca/pynacl#302]
Hi,

I am running into an issue where installing pynacl on a raspberry pi or in a multiarch docker container is very slow.  By default, `make` (https://github.com/pyca/pynacl/blob/master/setup.py#L163) is run in one thread.  Compile times could be reduced substantially (from >10 minutes to 1 minute in testing) by passing `-j4` or higher to `make`.

Would the maintainers entertain the idea of an environment variable such as `LIBSODIUM_MAKE_ARGS` which could be passed like `LIBSODIUM_MAKE_ARGS=-j4 pip install pynacl`?

**Comment by reaperhulk** [comment]
Yes I would be willing to review and merge such a patch.

**Comment by uSpike** [comment]
Thanks for merging.  Sorry for the noise, but just wondering when a new release might be done which contains this patch?

**Comment by reaperhulk** [comment]
We'll ship this with 1.2.0, which will hopefully be ready in a week or two!

**Comment by Ajaythepower1606** [comment]
Brother it is really takeing too much time to install 

It is showing 
Building wheel for pynacl (PEP 517) ... -

**Comment by Ajaythepower1606** [comment]
It had taken more then 30min but still installing
