### ISSUE TITLE
Python Wheel for ARM (Raspberry Pi) processor

### ISSUE THREAD

**Issue by mishas** [pyca/pynacl#306]
Looking at the [pypi page](https://pypi.python.org/pypi/PyNaCl/) for the project, there are many precompiled python wheels for different systems, but none for ARM (Raspberry Pi).

I'm working on a project with many Raspberry Pis involved, and it seems like running `pip3 install pynacl` takes ~20 minutes (!!!).

Interestingly enough, trying to compile it under emulation (qemu) it took even longer (~25 minutes).

It seems like Bug #302 helps a little bit, but not enough :(

Would it be possible to have a prebuilt Python Wheel for ARM as well?

Thanks.

**Comment by alex** [comment]
We don't have access to any ARM servers, so I don't think is going to be possible.

**Comment by mishas** [comment]
Would you consider cross compiling that via Docker?

Here's a simple Dockerfile that would work:
```
FROM resin/armv7hf-debian

RUN apt-get update \
 && apt-get install -y python3-dev python3-pip libffi-dev build-essential \
 && pip3 install wheel

WORKDIR /root/

CMD ["python3", "./setup.py", "bdist_wheel"]
```

Put this file in the root directory of the project and run:
```
> docker build -t pynacl_builder .
> docker run --rm -v `pwd`:/root/ pynacl_builder
```

Thanks again!

**Comment by reaperhulk** [comment]
We couldn't supply ARM based packages even if we wanted to because PyPI only allows uploading of specific "known safe" wheel types. Linux ARM wheels are not among that list (in fact, for linux only `manylinux1` is allowed). If you wanted that to change you'd need to engage with the PyPA to begin creating an ARM manylinux spec.
