### ISSUE TITLE
Expose ChaCha20Poly1305

### ISSUE THREAD

**Issue by reaperhulk** [pyca/pynacl#308]
https://download.libsodium.org/doc/secret-key_cryptography/chacha20-poly1305.html

😀

**Comment by lmctv** [comment]
Since, with regards to ChaCha20Poly1305, libsodium seems a bit "openssl-ish", are you thinking about binding and exposing one variant for a specific need you want to fulfill, or the whole set of three (maybe one by one).

**Comment by reaperhulk** [comment]
Probably IETF variant first wait to see if anybody requests the other two?

**Comment by maqp** [comment]
`The original construction can safely encrypt up to 2^64 messages with the same key, without any practical limit to the size of a message (up to 2^70 bytes).`

`The IETF variant. It can safely encrypt a pratically unlimited number of messages (2^96), but individual messages cannot exceed 64*(2^32)-64 bytes (approximatively 256 GB).`


2^64 messages in original construction last for 100 years (100×365.25×24×3600s) at rate of 5,845,420,460 packets / second. I think users are going to want to encrypt larger plaintexts sooner than they are going to want to exceed that output rate. So my vote would go to original implementation as long as compatibility over IETF variant isn't an issue.

**Comment by reaperhulk** [comment]
The IETF variant is presumably RFC 7539 which would make it compatible with output from several other crypto libs (including pyca/cryptography), although we'd need to confirm that.

**Comment by lmctv** [comment]
@maqp keep in mind all of these constructions are two-pass, don't provide a init/update/final interface, and therefore consume memory (at least) for something more than twice the message size. I don't expect anybody would encrypt messages bigger than 4GiB with this kind of interface any time soon!

**Comment by maqp** [comment]
@reaperhulk If that's the case then IETF variant is fine by me.

@lmctv Agreed. I admit I did not think this through. Disk encryption can't use stream ciphers anyway, and users are unlikely to send 256GB plaintexts for at least a decade or two.

**Comment by lmctv** [comment]
@maqp after the upgrade to 1.0.14 of the bundled version #318, we can start looking at adding bindings for the crypto_sign_{init,update,final} prehashed ed25519ph signatures

**Comment by jedisct1** [comment]
The secretstream API was recently introduced to improves this.

Under the hood, it's the IETF version of ChaCha20Poly1305, and a very simple mode that can be reimplemented using other libraries. An AES-GCM based version will follow, with the exact same interface, so you don't have to worry about memory requirements and key rotation.

**Comment by maqp** [comment]
@reaperhulk @lmctv Is this issue still supposed to be open?

**Comment by lmctv** [comment]
This can either be closed, since the bindings for all the chacha20 variants are in, or stay open as a reminder until we properly design and expose a high level API. Your call.

**Comment by maqp** [comment]
Ah, so the `nacl.bindings.crypto_aead_xchacha20poly1305_ietf_encrypt` isn't the final API. Very well. In that case I  think this should stay open.

**Comment by lmctv** [comment]
To clarify: the nacl.bindings level API is final; what's still to decide is if we also want to expose an higher-level wrapper at the nacl.secret level. I'm closing this issue, since it's just a confusion generator.
