### ISSUE TITLE
Grant lmctv commit bit

### ISSUE THREAD

**Issue by reaperhulk** [pyca/pynacl#309]
lmctv has been doing great work and is almost single-handedly pushing forward PyNaCl at the moment. I'd like to nominate him for commit access to pynacl.

@lmctv, Python Cryptographic Authority projects have strict rules about never merging your own PRs, so in practice your work will still be gated on reviews (sorry!), but having you be able to approve/merge other PRs as well as help triage and close issues would be very useful.

cc @alex @dstufft @warner

**Comment by lmctv** [comment]
I really appreciate the "don't merge by yourself" rule; happy to continue helping in triage and in trying to review, even though to date my review experience in public projects is been on the receiving side.

**Comment by alex** [comment]
You'll also need to ensure you have 2fa enabled on your github account.

**Comment by lmctv** [comment]
OK, enabled 2fa.

**Comment by reaperhulk** [comment]
Oof, this fell off my radar and GitHub doesn't notify you when there's a reaction. Looks like we have approval. I've added you!

**Comment by lmctv** [comment]
@reaperhulk , @alex I feel honoured. Thank you very much.
