### ISSUE TITLE
PyNaCl installation triggers easy_install

### ISSUE THREAD

**Issue by jobec** [pyca/pynacl#321]
When installing PyNaCl with pip, it will trigger an easy_install step because of the use of ``setup_requires``  in ``setup.py``. This breaks the installation when installing from a local/internal PyPi server with the error:

```
      ...
      File \"/home/test/.venv/lib/python3.4/site-packages/setuptools/command/easy_install.py\", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.4.1')
```
This issue seems to be bypassed in the [setup.py from cryptography](https://github.com/pyca/cryptography/blob/765a3e494e8196370995d2c698b6eda8492935e0/setup.py#L104)

**Comment by lmctv** [comment]
Are you sure setuptools can find a copy of cffi on your internal PyPi server?

**Comment by jobec** [comment]
Well, it can't indeed, although it's there and can be installed just fine with pip.

Eventually I traced the issue back to the fact that easy_install/setuptools doesn't take any settings from pip. After setting a index server in `.pydistutils.cfg` things started working.

https://docs.python.org/3/install/index.html#inst-config-files
http://setuptools.readthedocs.io/en/latest/easy_install.html

**Comment by lmctv** [comment]
@dstufft do you know where I can find some note/how-to on private PyPI indexes? If possible, I'd add a link to such notes in the Installation section of PyNaCl docs.
@jobec could you please tell us the versions of pip, setuptools and python versions both on the failing installation environment, and on the index server?

**Comment by jobec** [comment]
I did some more tests and it looks like I cannot replicate it anymore with a recent version of setuptools (>=23.0.0, but could not test versions older then that).

If I left the default version for CentOS 7.3 installed (0.9.8), it failed.

**Comment by lmctv** [comment]
Closin, since this seems to be an environment quick we have no control on.
