### ISSUE TITLE
Rename From PyNaCl to Sodium?

### ISSUE THREAD

**Issue by dstufft** [pyca/pynacl#34]
We don't actually wrap NaCl anymore and instead we depend on libsodium. Sodium started out as just a portable NaCl but it now includes things that NaCl doesn't. Additionally the NaCl name is easy to confuse with google's Native Client.

**Comment by codethief** [comment]
I got here because I was confused, too.

Bad name suggestion: libpodium?

**Comment by atralheaven** [comment]
at least change "NaCl" in "Python binding to the Networking and Cryptography (NaCl)" to libpodium! I was confused too. I thought you're using NaCl, Im happy that I see its libpodium, not NaCl. please make it clear everywhere that you're using libpodium, not NaCl.

**Comment by lmctv** [comment]
"libsodium" or simply "sodium" as the python package name?

**Comment by reaperhulk** [comment]
Changing the docs to note that it's libsodium based is a good idea. I'm against a name change due to the problems it would cause for any project currently depending on pynacl. I think we're stuck with the name.

**Comment by dstufft** [comment]
3 years ago when I opened this ticket it was a reasonable idea, now I agree it's a bad idea.

**Comment by reaperhulk** [comment]
Okay, not changing :)
