### ISSUE TITLE
Change default version of the doc on readthedocs

### ISSUE THREAD

**Issue by lmctv** [pyca/pynacl#351]
I think our users would be better served by the online documentation if we don't change our landing page on  rtd and set it to "stable" instead of "latest". As a matter of facts, @hoang408 added a note to issue #297 lamenting an exception while trying to import SealedBox since he was just trying to follow the example in upcoming 1.2 docs.

**Comment by lmctv** [comment]
@dstufft @warner: would you mind adding at least @alex and @reaperhulk as project owners on readthedocs?

**Comment by lmctv** [comment]
@warner @dstufft sorry for pinging, but the last correctly built version of the docs is missing the release date.

**Comment by lmctv** [comment]
@warner , @dstufft  PyNaCl docs at https://pynacl.readthedocs.io/en/latest/ are stuck at a pre-release commit of version 1.2. Would you mind authorizing at least @reaperhulk as an additional administrator for the project?

**Comment by warner** [comment]
Oops, yeah that's a great idea. I've just added @alex and @reaperhulk , and set the default version to "stable". Sorry for the delay!

**Comment by lmctv** [comment]
Many thanks, @warner . @reaperhulk we just miss enabling the "Install your project inside a virtualenv using setup.py install" flag and the CPython 3.x interpreter in the "Advanced Settings".

**Comment by reaperhulk** [comment]
Done.
