### ISSUE TITLE
Switch to using doctest for examples where appropriate

### ISSUE THREAD

**Issue by reaperhulk** [pyca/pynacl#356]
This will prevent issues like #352 from occurring in the future.
- [x] docs/hashing.rst
- [x] docs/public.rst
- [x] docs/secret.rst
- [x] docs/signing.rst
- [x] docs/password_hashing.rst

**Comment by lmctv** [comment]
The following rst files contain examples which should become doctests:
- [ ] docs/public.rst
- [ ] docs/secret.rst
- [ ] docs/signing.rst
- [ ] docs/password_hashing.rst

**Comment by lmctv** [comment]
@reaperhulk if you don't mind, I'd add the check list right in the issue opening comment, hopefully getting a progress indicator.

**Comment by lmctv** [comment]
All the code in documentation is tested now! Thanks @reaperhulk
