### ISSUE TITLE
1.2.0 release ETA?

### ISSUE THREAD

**Issue by spang** [pyca/pynacl#361]
Hi there! Thanks for your work on pynacl. I was wondering if there is any ETA for releasing 1.2.0, and if there's anything outside folks can do to help? A project I'm working on would greatly benefit from siphashx24.

**Comment by alex** [comment]
All the bugs in the milestone are closed. @reaperhulk / @lmctv are there any things that ought to go in that milestone?

**Comment by lmctv** [comment]
I'm discussing #357 with @reaperhulk , which would be a big change to the API I won't be comfortable in doing without a deprecation cycle after 1.2 . Any contribution to that discussion would surely be appreciated by myself, hopefully by @reaperhulk too...

**Comment by lmctv** [comment]
With #357 in and fixed, I think the only thing relly missing is a changelog entry; #362 would be nice, but it could wait, if @reaperhulk  and @alex feel so.

**Comment by reaperhulk** [comment]
I'm fine with doing a release whenever you want @lmctv. You've been driving this so once we merge a changelog and version bump I can run it for you.

**Comment by lmctv** [comment]
Just let me know if you'd prefer to conclude the review of #362 you've already started, or just go ahed with merging #365 to update the version; if at all possible, I think it would be better if @alex  could help the PR dance for adding the release date to the changelog, tagging and releasing to avoid time-zone induced lags.

**Comment by reaperhulk** [comment]
Let's finish #362. I'm actually on US central time for the next 6 days so time zone issues should be less of a problem :smile:

**Comment by lmctv** [comment]
Released on 2017-11-01. Binary wheels already available from pypi.

**Comment by spang** [comment]
thank you!
