### ISSUE TITLE
PIP installation failed on Windows 10 x64

### ISSUE THREAD

**Issue by rupesh28** [pyca/pynacl#388]
Trying to install using pip on Windows 10 x64 failed.. Below is the full log. Can someone help with how to resolve this?

Collecting pynacl
  Using cached PyNaCl-1.2.1.tar.gz
Requirement already satisfied: six in c:\users\default\appdata\local\programs\python\python37\lib\site-packages (from pynacl)
Requirement already satisfied: cffi>=1.4.1 in c:\users\default\appdata\local\programs\python\python37\lib\site-packages (from pynacl)
Requirement already satisfied: pycparser in c:\users\default\appdata\local\programs\python\python37\lib\site-packages (from cffi>=1.4.1->pynacl)
Installing collected packages: pynacl
  Running setup.py install for pynacl ... error
    Complete output from command c:\users\default\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\default\\AppData\\Local\\Temp\\pip-build-i711gqkc\\pynacl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\default\AppData\Local\Temp\pip-a2yzjdld-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\nacl
    copying src\nacl\encoding.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\exceptions.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\hash.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\hashlib.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\public.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\secret.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\signing.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\utils.py -> build\lib.win-amd64-3.7\nacl
    copying src\nacl\__init__.py -> build\lib.win-amd64-3.7\nacl
    creating build\lib.win-amd64-3.7\nacl\pwhash
    copying src\nacl\pwhash\argon2i.py -> build\lib.win-amd64-3.7\nacl\pwhash
    copying src\nacl\pwhash\argon2id.py -> build\lib.win-amd64-3.7\nacl\pwhash
    copying src\nacl\pwhash\scrypt.py -> build\lib.win-amd64-3.7\nacl\pwhash
    copying src\nacl\pwhash\_argon2.py -> build\lib.win-amd64-3.7\nacl\pwhash
    copying src\nacl\pwhash\__init__.py -> build\lib.win-amd64-3.7\nacl\pwhash
    creating build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_box.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_generichash.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_hash.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_pwhash.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_shorthash.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_sign.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\randombytes.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\sodium_core.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\utils.py -> build\lib.win-amd64-3.7\nacl\bindings
    copying src\nacl\bindings\__init__.py -> build\lib.win-amd64-3.7\nacl\bindings
    running build_clib
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\default\AppData\Local\Temp\pip-build-i711gqkc\pynacl\setup.py", line 251, in <module>
        "Programming Language :: Python :: 3.6",
      File "c:\users\default\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\default\appdata\local\programs\python\python37\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\default\appdata\local\programs\python\python37\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\default\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\default\appdata\local\programs\python\python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\default\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\default\appdata\local\programs\python\python37\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\default\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\default\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\default\appdata\local\programs\python\python37\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\default\AppData\Local\Temp\pip-build-i711gqkc\pynacl\setup.py", line 159, in run
        raise Exception("ERROR: The 'make' utility is missing from PATH")
    Exception: ERROR: The 'make' utility is missing from PATH

    ----------------------------------------
Command "c:\users\default\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\default\\AppData\\Local\\Temp\\pip-build-i711gqkc\\pynacl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\default\AppData\Local\Temp\pip-a2yzjdld-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\default\AppData\Local\Temp\pip-build-i711gqkc\pynacl\

**Comment by rupesh28** [comment]
Sorry.. duplicate. I found another one similar to this.

**Comment by lmctv** [comment]
I don't understand the reason why pip tried to build the package from sources instead of downloading the binary wheel, as expected. If you can, please edit the issue opening comment, inserting the pip command line you used and some more details about the environment this happened in. Thanks.
