### ISSUE TITLE
Strange difference in private key calculation from seed

### ISSUE THREAD

**Issue by peter-jung** [pyca/pynacl#394]
There is an interesting difference in the private key when calculated from the seed via two different paths with pynacl. We compare initializing PrivateKey() from a seed with initializing SigningKey() from the same seed and then calling to_curve25519_private_key(). 

I have used the seed from the `test_key_conversion()` test [here](https://github.com/pyca/pynacl/blob/master/tests/test_signing.py).

```
from nacl.public import PrivateKey
from nacl.signing import SigningKey
import binascii

keypair_seed = (b"421151a459faeade3d247115f94aedae"
                b"42318124095afabe4d1451a559faedee")
seed_b = binascii.unhexlify(keypair_seed)
print('seed', keypair_seed.decode())

private_key_1 = PrivateKey.from_seed(seed_b)
print('priv', binascii.hexlify(private_key_1.encode()).decode())

private_key_2 = SigningKey(seed = seed_b).to_curve25519_private_key()
print('sign', binascii.hexlify(private_key_2.encode()).decode())
```

The output is 

```
seed 421151a459faeade3d247115f94aedae42318124095afabe4d1451a559faedee
priv 8252030376d47112be7f73ed7a019293dd12ad910b654455798b4667d73de1e6
sign 8052030376d47112be7f73ed7a019293dd12ad910b654455798b4667d73de166
```

So there is a difference in the first and last bytes, only. Should this difference be expected? If so, why?

**Comment by peter-jung** [comment]
I tracked this down to be an implementation detail in LibSodium. It is due to _clamping_ (used to make the key more secure) that is applied before reporting the key from the SigningKey Object but not applied when reporting the key from the PrivateKey object.

**Comment by reaperhulk** [comment]
Thanks for investigating!
