### ISSUE TITLE
Build failures due to sanity checks (64bit-portability-issue)

### ISSUE THREAD

**Issue by frispete** [pyca/pynacl#401]
Hi, 

I'm creating [PyNaCl packages](https://build.opensuse.org/package/show/home:frispete:python/python-PyNaCl) on [openSUSEs Build Service](https://build.opensuse.org) for a bunch of different openSUSE distributions. With the latest release (and maybe earlier), PyNaCl fails due to sanity checks in the build system for almost all distributions, but Tumbleweed (a rolling release) due to:
```
[   43s] E: python-PyNaCl 64bit-portability-issue build/temp.linux-x86_64-2.7/_sodium.c:2711, 2721, 2975, 2985
[   43s] E: python-PyNaCl 64bit-portability-issue build/temp.linux-x86_64-3.4/_sodium.c:2711, 2721, 2975, 2985
```
These are triggered from compiler warnings like this:
```
[   34s] build/temp.linux-x86_64-3.4/_sodium.c: In function '_cffi_d_crypto_pwhash_argon2i_strprefix':
[   34s] build/temp.linux-x86_64-3.4/_sodium.c:2711:3: warning: implicit declaration of function 'crypto_pwhash_argon2i_strprefix' [-Wimplicit-function-declaration]
[   34s]    return crypto_pwhash_argon2i_strprefix();
[   34s]    ^
[   34s] build/temp.linux-x86_64-3.4/_sodium.c:2711:3: warning: return makes pointer from integer without a cast [enabled by default]
```
You can fetch the build log [here](https://build.opensuse.org/build/home:frispete:python/openSUSE_13.2/x86_64/python-PyNaCl/_log) and lookup the line numbers. The compile command is nearly identical in these environments, but there are different gcc versions at work of course, with all the implications related to the cffi infrastructure.

I've tried to track down the issue, but was lost in the maze of cffi defines. Obviously, gcc cannot locate the declaration of these functions, which are properly defined in crypto_pwhash.h. 

I can shut up gcc for these warnings, but it would be nice to solve this in a proper way, given the purpose of this package.

Any ideas anybody?

**Comment by lmctv** [comment]
Reading the specfile at https://build.opensuse.org/package/view_file/home:frispete:python/python-PyNaCl/python-PyNaCl.spec?expand=1, I see it's mandating use of the distribution-provided version of libsodium, instead of the pynacl-bundled one.

The symbols flagged as undeclared in the compile phase like `crypto_pwhash_alg_argon2id13` are not present in previous versions of the library, the compiler is right, and muting the warning would just help in building a non-functional package. Please try deleting the
```
export SODIUM_INSTALL="system"
```
line in the specfile, or replacing it with
```
export SODIUM_INSTALL="bundled"
```
As a matter of facts, while checking #417 on opensuse 42.3, and building pynacl in a fresh virtualenv, I haven't seen any warning coming out of the _sodium compile phase:
```
[ . . . ]
running build_ext
generating cffi module 'build/temp.linux-x86_64-2.7/_sodium.c'
already up-to-date
building '_sodium' extension
gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -Ibuild/temp.linux-x86_64-2.7/include -c build/temp.linux-x86_64-2.7/_sodium.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_sodium.o
gcc -pthread -shared build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_sodium.o -Lbuild/temp.linux-x86_64-2.7/lib -Lbuild/temp.linux-x86_64-2.7/lib64 -L/usr/lib64 -Lbuild/temp.linux-x86_64-2.7 -lsodium -lpython2.7 -lsodium -o build/lib.linux-x86_64-2.7/nacl/_sodium.so
installing to build/bdist.linux-x86_64/dumb
running install
[ . . . ]
```
