### ISSUE TITLE
build_clib Exception for libsodium/configure : No such file or directory - Termux on Nexus 7

### ISSUE THREAD

**Issue by Legarts** [pyca/pynacl#405]
Device: Asus Nexus 7 2012
App: Termux 

``pip install pynacl``

![screenshot_2018-02-10-21-18-04](https://user-images.githubusercontent.com/8315154/36066614-dacbff50-0eac-11e8-966b-ddc4802a4183.png)

I browsed through the previous issues and made sure that ``make``, along with clang and required libraries are installed.

**Comment by lmctv** [comment]
This is a build environment problem, and should be forwarded to the termux developers, which are the only ones who can fix the way the runtime environment works.
