### ISSUE TITLE
Slow randombytes

### ISSUE THREAD

**Issue by thestick613** [pyca/pynacl#412]
This line is slowing down `randombytes`, because it creates a new object every time it is ran.
https://github.com/pyca/pynacl/blob/master/src/nacl/bindings/randombytes.py#L28

Is there a different way to re-engineer this, so it runs faster?

**Comment by reaperhulk** [comment]
Not without having the user pass a reusable buffer. `(e.g. randombytes_into_buf(bytearray))` And even then it doesn't appear to be significantly faster based on my testing. What is your use case here?

**Comment by alex** [comment]
Also, do you have a benchmark that shows the allocation is the performance problem?

**Comment by thestick613** [comment]
```
#!/usr/bin/python

import os
import nacl.bindings
import nacl.utils
import numpy.random
import time

runs = 100000
l = 32

t0 = time.time()

for _ in range(runs):
#    nacl.bindings.randombytes(l)
    nacl.utils.random(l)

t1 = time.time()

for _ in range(runs):
    os.urandom(l)

t2 = time.time()

for _ in range(runs):
    numpy.random.bytes(l)

t3 = time.time()

print "nacl", t1-t0
print "osur", t2-t1
print "npra", t3-t2

```

```
nacl 0.138158082962
osur 0.0892460346222
npra 0.0348038673401

```

I'm profiling some code and `nacl.bindings.randombytes` seems to take a lot of time. I'm aware that os.urandom and numpy are probably not crypto secure.

**Comment by alex** [comment]
Numpy is not cryptographically secure, but `os.urandom` is.

**Comment by lmctv** [comment]
Do you really need to generate thousands of keys or cryptographically strong nonces per second? Keep in mind that nacl.bindings.randombytes is implemented as a means to minimize the pressure on the system's RNG, and the risk to incur in blocking behavior, and therefore cannot be directly compared to is.urandom.

**Comment by alex** [comment]
"minimize the pressure on the system's RNG" is nonsense; using os.urandom for all key generation should be fine, that's what pyca/cryptography does.

Is there a reason to expose nacl's RNG or can we just make it call `os.urandom` and call it a day?

**Comment by lmctv** [comment]
While I agree in the python case binding randombytes looks redundant, I seem to understand the project has always tried to keep pynacl API mostly in line with our lib{nacl,sodium} upstream and the other languages' bindings. I wouldn't object to a PR rewriting nacl.utils.random or even nacl.bindings.randombytes in terms of os.urandom, but I think the API should stay.

**Comment by lmctv** [comment]
#413 replaced nacl.bindings.randombytes with os.urandom in the high level API.
