### ISSUE TITLE
Support for HACL

### ISSUE THREAD

**Issue by oberstet** [pyca/pynacl#423]
[HACL](https://github.com/mitls/hacl-star) is a formally verified cryptographic library in F* that provides the same crypto primitives as NaCl, and that transpiles to C, claiming to export the same API as libsodium.

It is also fast:

> For most primitives, our HACL implementations are as fast as (and sometimes faster than) the fastest unvectorized C implementations in OpenSSL, Libsodium, and SUPERCOP. Notably, all our code is significantly faster than the naive reference implementations included in TweetNaCl and SUPERCOP. However, some assembly implementations and vectorized C implementations are faster than HACL.

From: https://eprint.iacr.org/2017/536.pdf

So it would be great to be able to plug HACL into PyNaCl instead of libsodium.

**Comment by lmctv** [comment]
Quoting from HACL repository's readme "Warning: libsodium also implements other algorithms not in NaCl that are not implemented by HACL*".

Since PyNaCl binds more than what HACL* implements, I'm closing this issue.

Feel free to open a new issue if/when HACL will implement all the bound APIs .

**Comment by oberstet** [comment]
I have not looked into what exactly is missing in HACL compared to NaCl (maybe mainly the password hashing stuff). My use of PyNaCl is pretty much confined to a very narrow high-level API (cryptobox/cryptosign) which is indeed available in HACL. So maybe I should just create HACL cffi bindings for what I need ..
