### ISSUE TITLE
Building pynacl fails in Python 3.7

### ISSUE THREAD

**Issue by ThreePinkApples** [pyca/pynacl#441]
```
(py37) oheddela@OHEDDELA-JA30E:/mnt/c/Users/oheddela/dev$ pip install pynacl
Looking in indexes: http://qa-devpi.rd.*.com/labuser/itvm
Collecting pynacl
  Downloading http://qa-devpi.rd.*.com/root/pypi/+f/e0d/38fa0a75f65f5/PyNaCl-1.2.1.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 29.9MB/s
Requirement already satisfied: six in /home/oheddela/.virtualenvs/py37/lib/python3.7/site-packages (from pynacl) (1.11.0)
Requirement already satisfied: cffi>=1.4.1 in /home/oheddela/.virtualenvs/py37/lib/python3.7/site-packages (from pynacl) (1.11.5)
Requirement already satisfied: pycparser in /home/oheddela/.virtualenvs/py37/lib/python3.7/site-packages (from cffi>=1.4.1->pynacl) (2.18)
Building wheels for collected packages: pynacl
  Running setup.py bdist_wheel for pynacl ... \
```

It's simply just stuck there, on 'Running setup.py bdist_wheel for pynacl'.
Edit: No building in PY3.6 because it just uses the wheel from PyPi
```
(py37) oheddela@OHEDDELA-JA30E:/mnt/c/Users/oheddela/dev$ python -V
Python 3.7.0rc1
(py37) oheddela@OHEDDELA-JA30E:/mnt/c/Users/oheddela/dev$ pip --version
pip 10.0.1
setuptools (39.2.0)  INSTALLED: 39.2.0 (latest)
```

Tried installing from source, got GCC error, so maybe not Python 3.7 releated really:

```
Installing collected packages: PyNaCl
  Running setup.py develop for PyNaCl
    Complete output from command /home/oheddela/.virtualenvs/py37/bin/python3.7 -c "import setuptools, tokenize;__file__='/mnt/c/Users/oheddela/dev/pynacl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing src/PyNaCl.egg-info/PKG-INFO
    writing dependency_links to src/PyNaCl.egg-info/dependency_links.txt
    writing requirements to src/PyNaCl.egg-info/requires.txt
    writing top-level names to src/PyNaCl.egg-info/top_level.txt
    reading manifest file 'src/PyNaCl.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/install.sh'
    warning: no previously-included files found matching '.travis/run.sh'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'tasks.py'
    warning: no previously-included files found matching 'Jenkinsfile'
    warning: no previously-included files found matching '.jenkins'
    warning: no previously-included files found matching '.jenkins/Jenkinsfile-pynacl-wheel-builder'
    writing manifest file 'src/PyNaCl.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.7/_sodium.c'
    creating build
    creating build/temp.linux-x86_64-3.7
    building '_sodium' extension
    creating build/temp.linux-x86_64-3.7/build
    creating build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.7m -Ibuild/temp.linux-x86_64-3.7/include -c build/temp.linux-x86_64-3.7/_sodium.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/_sodium.o
    build/temp.linux-x86_64-3.7/_sodium.c:492:10: fatal error: sodium.h: No such file or directory
     #include <sodium.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

**Comment by ThreePinkApples** [comment]
Found this comment: https://github.com/nylas/sync-engine/issues/95#issuecomment-60168042
Installed libsodium-dev, building fine now :)

**Comment by JFriesenhahn** [comment]
> Found this comment: [nylas/sync-engine#95 (comment)](https://github.com/nylas/sync-engine/issues/95#issuecomment-60168042)
> Installed libsodium-dev, building fine now :)

Thanks -- this was really helpful. For anyone else looking for a solution, I needed to do this + used the packaged version as part of the install via the "SODIUM_INSTALL=system pip install pynacl" line mentioned at https://pynacl.readthedocs.io/en/stable/install/.

**Comment by jxub** [comment]
I had the same issue, solved weirdly with doing a `pip3 install setuptools`

**Comment by lmctv** [comment]
Would you mind giving some more information about about your build/execution environment? In particular:
 - OS
 - if linux, distribution, complete with version and CPU architecture
 - python version and installation origin (OS package, other pre-built binary distribution, self compiled from source)
Thanks

**Comment by lennyx-git** [comment]
> > Found this comment: [nylas/sync-engine#95 (comment)](https://github.com/nylas/sync-engine/issues/95#issuecomment-60168042)
> > Installed libsodium-dev, building fine now :)
> 
> Thanks -- this was really helpful. For anyone else looking for a solution, I needed to do this + use the packaged version as part of the install via the "SODIUM_INSTALL=system pip install pynacl" line mentioned at https://pynacl.readthedocs.io/en/stable/install/.

Thanks Mate, after adding that variable, I was able to finally install pynacl under cygwin which was required by junos-eznc module, also installed libsodium-devel under cygwin GUI installer.

Two lines resolved my issue:
export SODIUM_INSTALL=system
pip3 install --no-binary :all: pynacl

or (if you want to install Junos PyEZ which requires pynacl)

pip3 install --no-binary :all: junos-eznc

**Comment by jxub** [comment]
@lmctv Sorry for responding just now.

OS was macOS Mojave and I've installed Python with Homebrew. Sorry for not sharing more details but this was on a work laptop from my previous job.
