### ISSUE TITLE
is it possible to run commands on a device which is two servers away from our PC in Python

### ISSUE THREAD

**Issue by Nirosh-123** [pyca/pynacl#443]
Hello Guys

I want to run python script in PC to connect to a router which can be accessed via jump server, and the command out put should come my PC ,below is the scenario.if it possible how to do it in Python.

![image](https://user-images.githubusercontent.com/40388318/41672734-4a5e91c0-74d8-11e8-8d45-573d51bafb50.png)

Thanks in Advance

**Comment by alex** [comment]
This bug tracker is for the pynacl library. Your question is a general programming/python question, so this isn't an appropriate forum for it.

**Comment by Nirosh-123** [comment]
thanks alex, I will post it on right forum
