### ISSUE TITLE
Use PEP 518 pyproject.toml to require cffi

### ISSUE THREAD

**Issue by segevfiner** [pyca/pynacl#453]
Using `setup_requires` triggers installation of `cffi` using the old and crusty `easy_install`, which often doesn't work well if at all.

[PEP 518](https://www.python.org/dev/peps/pep-0518/#file-format) allows specifiying this requirements in a `pyproject.toml` file, which pip 10 recognizes and will install those requirements itself.

**Comment by alex** [comment]
`pyproject.toml` only works with packages that are installed as wheels right now. Since `cffi` isn't always available as a wheel, we can't do this yet.

**Comment by segevfiner** [comment]
> pyproject.toml only works with packages that are installed as wheels right now. Since cffi isn't always available as a wheel, we can't do this yet.
What do you mean? The latest pip installs everything as a wheel, if it can. If a wheel isn't available from PyPI, it builds a wheel first and installs that.

I think using `pyproject.toml` makes it build the wheel in a virtualenv containing only the specified packages.

Is there really a problem with this behavior?

**Comment by alex** [comment]
pip will not attempt to build a wheel for a dependency in `pyproject.toml` if there is only an `sdist` available.

**Comment by segevfiner** [comment]
A new version of pip was released where source installs from PEP 518 is now supported. (https://github.com/pypa/pip/pull/5336). I didn't yet get to check if it works properly.

**Comment by reaperhulk** [comment]
#457 does this
