### ISSUE TITLE
Error on dlopen - Mac Os 10.6.8

### ISSUE THREAD

**Issue by gregoriopellegrino** [pyca/pynacl#461]
Hi,
I'm trying to use pynacl on mac os 10.6.8, but I get:

ImportError: dlopen(/usr/local/lib/python3.7/site-packages/nacl/_sodium.abi3.so, 2): Symbol not found: _memset_s
  Referenced from: /usr/local/lib/python3.7/site-packages/nacl/_sodium.abi3.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.7/site-packages/nacl/_sodium.abi3.so

Can you help me fixing it?

Gregorio

**Comment by alex** [comment]
I don't think we have an official macOS support policy, but you should _really_ upgrade to a newer macOS release. 10.6 has not been receiving security updates for many years, and most things no longer support it (e.g. both Firefox and Chrome do not).

**Comment by reaperhulk** [comment]
It's possible the current wheel won't work with such an ancient system. You can do `pip install --no-binary pynacl pynacl` to try to compile it yourself, but we can't support an OS this old.
