### ISSUE TITLE
Release 1.2.2 including all non breaking changes

### ISSUE THREAD

**Issue by evilaliv3** [pyca/pynacl#462]
Pynacl 1.2.1 is already packaged and included in Debian Stretch and Ubuntu Bionic that are current Debian and Ubuntu LTS versions respectively.

As well the two distributions include libsodium 1.6

I would be of great value, before issuing a new 1.3.0 version including possible breaking changes, to issues a release 1.2.2 that could be packaged and released for those distributions.

I've reviewed the current CHANGELOG for 1.3.0 and it seems to me that none of the changes is a breaking changes but i may wrong.

I'm writing this while planning adoption of pynacl in GlobaLeaks where secret stream would be of great value to have the possibility to perform file encryption in streaming benefiting of the binding of  crypto_secretstream_xchacha20poly1305 https://github.com/pyca/pynacl/pull/460

**Comment by evilaliv3** [comment]
Thanks for your feedback @lmctv, that is totally understandable! 

In the meantime for the specific need of implementing streaming in pynacl 1.2 the valid option remains the one of @dchest: https://github.com/kaepora/miniLock/issues/2#issuecomment-49586396

**Comment by maqp** [comment]
I'm also in favor of releasing an intermediary version as it would feature the `crypto_aead_xchacha20poly1305_ietf_*` bindings I have use for.

**Comment by maqp** [comment]
@evilaliv3 I think this can be closed now :confetti_ball:

**Comment by evilaliv3** [comment]
I'm sorry for checking it only now.

It would have been important to have this released in a 1.2.2 to make it available already in the strech backports: https://packages.debian.org/stretch-backports/python-nacl

But thank you for having made it so that it at least entered in current sid.
