### ISSUE TITLE
'SecretBox' object has no attribute 'MACBYTES'

### ISSUE THREAD

**Issue by L3rchal** [pyca/pynacl#478]
I was following this example here on your docs: https://pynacl.readthedocs.io/en/stable/secret/

and this line `assert len(encrypted) == len(message) + box.NONCE_SIZE + box.MACBYTES` gave me this error: `AttributeError: 'SecretBox' object has no attribute 'MACBYTES'`

`PyNaCl                   1.2.1`
`Python 3.7`

**Comment by reaperhulk** [comment]
MACBYTES was added (https://github.com/pyca/pynacl/commit/8556486e586b2955aa7a85c4fb91b28119be0141#diff-39ba8f7b8fa8f1904cd53066dabc278b) in 1.3.0 which was just released
