### ISSUE TITLE
Missing wheels

### ISSUE THREAD

**Issue by djw** [pyca/pynacl#479]
Hi,

It looks like the 1.3.0 release is missing some of its wheels. When attempting to install this version on Debian Stretch, I now have to compile from source.

Compare

https://pypi.org/project/PyNaCl/#files

with 

https://pypi.org/project/PyNaCl/1.2.1/#files

I suspect related to #449.

**Comment by reaperhulk** [comment]
This isn't #449 but it is an issue. We released 1.3.0 but our tooling to build the abi3 wheels failed due to a change in the way pip 18 handles dependent wheels. I'll be uploading the missing wheels soon.

**Comment by reaperhulk** [comment]
Fixed
