### ISSUE TITLE
Stuck at Running setup.py bdist_whell for pynacl

### ISSUE THREAD

**Issue by fewknow** [pyca/pynacl#486]
$ pip install pynacl
Collecting pynacl
  Using cached https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz
  Installing build dependencies ... done
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from pynacl) (1.10.0)
Requirement already satisfied: cffi>=1.4.1 in /usr/lib/python2.7/site-packages (from pynacl) (1.11.5)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->pynacl) (2.17)
Building wheels for collected packages: pynacl
  Running setup.py bdist_wheel for pynacl ... \

I am going to let it this run to see if it will complete, but as of now it has been 10 minutes.

Is there another library that should be installed to speed this up? 

Thanks

**Comment by alex** [comment]
You'll generally get a faster install with a wheel -- make sure you have the latest pip and setuptools installed.

Otherwise we need to build libsodium, which can take some time.

**Comment by yangxuan8282** [comment]
Stuck at same place, the server is freezing, never got issues when I compiling other packages(include chromium).

**Comment by ciprian-barbu** [comment]
FYI:
https://github.com/jedisct1/libsodium/issues/890

In short, in my case, mmap would try to map an enormous amount of memory and eventually fail. I also had vm.memory_overcommit set to 1, setting it to 0 or 2 should fix the problem.

It would be really nice if PyNaCl moved to an earlier version of libsodium, as 1.0.16 is at least an year old.
