### ISSUE TITLE
How to load SigningKey from its serialized value?

### ISSUE THREAD

**Issue by fgRuslan** [pyca/pynacl#501]
For example, I have serialized it to string:
c0e184c81e3c8b8664ade34aa8f87b6727233dc12ad72df113563baeb99e8a2c

But how to load it from this string? The SigningKey constructor expects a seed, but not the value.
What should I do?

**Comment by fgRuslan** [comment]
Help me pls

**Comment by lmctv** [comment]
Taking a guess from the alphabet and size of the serialized string, it is possible you saved the output of the encode() method on a nacl.signing.SigningKey instance as in:
```
>>> import nacl.encoding, nacl.signing
>>> sk = nacl.signing.SigningKey.generate()
>>> hexseed = sk.encode(encoder=nacl.encoding.HexEncoder)
>>> print(hexseed)
b'21ef1c548aa573dd270eab70f6842b1e81548096a34446f87a430db318efb096'
```
If this is the case, the saved string is just the hexadecimal encoding of the seed, and you can just deserialize it with something like:
```
>>> SK = nacl.signing.SigningKey(hexseed, encoder=nacl.encoding.HexEncoder)
```
To convince yourself on SK being the same as sk, you could encode SK and verify its encoding is the same as the one from sk:
```
>>> hexseed2 = SK.encode(encoder=nacl.encoding.HexEncoder)
>>> assert hexseed2 == hexseed
```
or check the equality of the respective VerifyKey
```
>>> assert sk.verify_key == SK.verify_key
```
If this is the case, the VerifyKey derived from the encoded secret you posted would be:
```
>>> SK = nacl.signing.SigningKey(b'c0e184c81e3c8b8664ade34aa8f87b6727233dc12ad72df113563baeb99e8a2c', encoder=nacl.encoding.HexEncoder)
>>> SK.verify_key.encode(encoder=nacl.encoding.HexEncoder)b'9e933a6f4142ac06d2625625747ac117ef3998e9d2a8fef4f578ddc5e18e6908'
```

**Comment by lmctv** [comment]
**Very important warning**: in public key cryptography, keeping the secrecy of the secret key component is of paramount importance. It would therefore be better if you could avoid direct serialisation of the secret, and instead used a password based key derivation[1] either to generate the secret at runtime, or to wrap the public key secret in a shared/symmetric key cryptographic envelope.

[1] https://pynacl.readthedocs.io/en/stable/password_hashing/
