### ISSUE TITLE
Solaris: import pynacl.bindings fails with "referenced symbol not found"

### ISSUE THREAD

**Issue by wiggin15** [pyca/pynacl#502]
I'm having trouble getting PyNaCl to work on Solaris. After installation, import fails to load the shared object `_sodium.so` with the message "symbol sodium_unpad: referenced symbol not found".
I am using the "embedded" libsodium, as I won't be able to install libsodium itself on my target machines.

I reproduces this issue on Solaris 10.11 and Solaris 11.2, on both SPARC and x64 architectures, with or without the "-m32" CFLAG (during installation), and on Python 2 and 3.

```
root@host-ci037 (SunOS 5.11) ➜  ~  pip install pynacl
Looking in indexes: https://pypi.org/simple/
Collecting pynacl
  Downloading https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz (3.4MB)
    100% |████████████████████████████████| 3.4MB 663kB/s
  Installing build dependencies ... done
Requirement already satisfied: six in ./python/lib64/python2.7/site-packages/six-1.12.0-py2.7.egg (from pynacl) (1.12.0)
Requirement already satisfied: cffi>=1.4.1 in ./python/lib64/python2.7/site-packages/cffi-1.11.5-py2.7-solaris-2.11-i86pc.64bit.egg (from pynacl) (1.11.5)
Requirement already satisfied: pycparser in ./python/lib64/python2.7/site-packages/pycparser-2.19-py2.7.egg (from cffi>=1.4.1->pynacl) (2.19)
Installing collected packages: pynacl
  Running setup.py install for pynacl ... done
Successfully installed pynacl-1.3.0


root@host-ci037 (SunOS 5.11) ➜  ~  python -c "import nacl.bindings"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/python/lib64/python2.7/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "/root/python/lib64/python2.7/site-packages/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: ld.so.1: python2.7: fatal: relocation error: file /root/python/lib64/python2.7/site-packages/nacl/_sodium.so: symbol sodium_unpad: referenced symbol not found
```

Any ideas?
Thanks

**Comment by lmctv** [comment]
Could you please try running
```
# ldd -r /root/python/lib64/python2.7/site-packages/nacl/_sodium.so
```
to see what dynamic library the bindings are linked to?

**Comment by wiggin15** [comment]
I tried to build PyNaCl from source, and noticed that there is a warning at the end of the build:
`file build/temp.solaris-2.11-i86pc.64bit-2.7/lib/libsodium.a(libsodium_la-aead_chacha20poly1305.o): wrong ELF class: ELFCLASS32`
([here](https://gist.github.com/wiggin15/ebcd239f7a858ed09ac54d23e188e279) is the full output). 
It looks like the extension `_sodium.so` compiles with `-m64` and the rest of the options that come from `sysconfig` (I found the compiler and linker flags used for it in `import sysconfig; sysconfig.get_config_vars()`), but libsodium itself does not use this configuration when compiling, so it links as 32-bit. I verified this by using `ar -x` on `libsodium.a` and using `file` on the `o` files it contained (e.g. `libsse2_la-salsa20_xmm6int-sse2.o:      ELF 32-bit LSB relocatable 80386 Version 1`).

Then I tried running
`LDFLAGS=-m64 CFLAGS=-m64 python setup.py install`
to force libsodium to compile with 64 bit. This time the o files in libsodium.a showed 64-bit and the warning was gone. Now it still doesn't work but the error is a little different:

`ImportError: ld.so.1: python2.7: fatal: relocation error: file /root/python/lib64/python2.7/site-packages/PyNaCl-1.3.0-py2.7-solaris-2.11-i86pc.64bit.egg/nacl/_sodium.so: symbol __stack_chk_guard: referenced symbol not found`

ldd shows this:
```
root@host-ci037 (SunOS 5.11) ➜  ~  ldd -r /root/python/lib64/python2.7/site-packages/PyNaCl-1.3.0-py2.7-solaris-2.11-i86pc.64bit.egg/nacl/_sodium.so
        libpython2.7.so.1.0 =>   /root/python/lib64/python2.7/site-packages/PyNaCl-1.3.0-py2.7-solaris-2.11-i86pc.64bit.egg/nacl/../../../../libpython2.7.so.1.0
        libgcc_s.so.1 =>         /usr/lib/64/libgcc_s.so.1
        libc.so.1 =>     /lib/64/libc.so.1
        libz.so =>       /root/python/lib64/libz.so
        libsocket.so.1 =>        /lib/64/libsocket.so.1
        libnsl.so.1 =>   /lib/64/libnsl.so.1
        libdl.so.1 =>    /lib/64/libdl.so.1
        libm.so.2 =>     /lib/64/libm.so.2
        libmp.so.2 =>    /lib/64/libmp.so.2
        libmd.so.1 =>    /lib/64/libmd.so.1
        libsoftcrypto.so.1 =>    /lib/64/libsoftcrypto.so.1
        libelf.so.1 =>   /lib/64/libelf.so.1
        libcryptoutil.so.1 =>    /lib/64/libcryptoutil.so.1
        libz.so.1 =>     /lib/64/libz.so.1
        symbol not found: __stack_chk_guard             (/root/python/lib64/python2.7/site-packages/PyNaCl-1.3.0-py2.7-solaris-2.11-i86pc.64bit.egg/nacl/_sodium.so)
        symbol not found: __stack_chk_fail              (/root/python/lib64/python2.7/site-packages/PyNaCl-1.3.0-py2.7-solaris-2.11-i86pc.64bit.egg/nacl/_sodium.so)
```

**Comment by wiggin15** [comment]
I managed to solve this by adding `--disable-ssp` to the flags that `setup.py` passes to libsodium's `configure`, in addition to using `CLFAGS=-m64 LDFLAGS=-m64` environment variables when calling `setup.py install`.

Please consider using this flag and reading the environment variables from `sysconfig` when compiling libsodium. In the meantime I will build local wheels for use in our Solaris systems.
Thank you!

**Comment by reaperhulk** [comment]
Hmm, for some reason I thought cffi modules built under the same config vars that Python was built with by default, but evidently that's not the case?

**Comment by lmctv** [comment]
The mismatch is between python an cffi on one side, and the building of the embedded libsodium.
Would you mind showing us the main build-time sysconfig values on your installed python:
```
>>> import sysconfig
>>> sysvars = sysconfig.get_config_vars()
>>> print(sysvars['CC'])
>>> print(sysvars['CFLAGS'])
>>> print(sysvars['CCSHARED'])
```
Thank you.

**Comment by lmctv** [comment]
@rjmarshall17, @qdavidle , could you also try showing the output obtained from your respective python installations?

**Comment by wiggin15** [comment]
I'm using a self-compiled version of Python from our [relocatable-python](https://github.com/Infinidat/relocatable-python) project - that's why there are some `-I` flags (they are dynamically changed to match the python install directory).

```
>>> import sysconfig
>>> sysvars = sysconfig.get_config_vars()
>>> print(sysvars['CC'])
gcc
>>> print(sysvars['CFLAGS'])
-fno-strict-aliasing -I/root/python/include -m64 -I/root/python/include/gnutls -I/root/python/include/graphviz -I/root/python/include/libexslt -I/root/python/include/libxml2 -I/root/python/include/libxslt -I/root/python/include/ncurses -I/root/python/include/openssl -I/root/python/include/readline -I/root/python/include/sasl -I/root/python/lib64/libffi-3.2.1/include -DNDEBUG -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -m64
>>> print(sysvars['CCSHARED'])
-fPIC
```
