### ISSUE TITLE
How to serialize SignedMessage?

### ISSUE THREAD

**Issue by fgRuslan** [pyca/pynacl#508]
I need to serialize it to add it in a JSON object and load it from JSON object later.
How to do it?

**Comment by sseering** [comment]
You problem doesn't sound like its is related to PyNaCl.

Have a look at the Python standard library documentation: https://docs.python.org/3/library/stdtypes.html#binary-sequence-types-bytes-bytearray-memoryview

There you will find ways to convery bytes into strings. Strings can be serialized using JSON.

**Comment by lmctv** [comment]
You can take inspiration from the way hexadecimal serialized test vectors in  `tests/data/ed25519` are serialized and deserialized from/to bytes using either the binascii.{hex,unhex,}lify couple or nacl.encoding.HexEncoder.

The usual way followed to encode binary data for embedding in json containers is base 64, for which you could use either nacl.encoding.Base64Encoder or base64.b64{de,en}code.
