### ISSUE TITLE
Building for Android

### ISSUE THREAD

**Issue by atoms118** [pyca/pynacl#510]
Specifically, I'm hoping to use the Chaquopy library. Compiling libsodium is already very straightforward, it's only the Python bindings that have been causing trouble for me.

**Comment by atoms118** [comment]
Ok so to clarify, I'm willing to work on this but I need to know how to build the `_sodium.abi3.so` file; like I said before, building libsodium itself with the Android NDK is already well documented and straightforward enough, so it's only that one file I need to know how to build.

**Comment by mhsmith** [comment]
A pre-built PyNaCl is now available for Chaquopy (https://github.com/chaquo/chaquopy/issues/85).

**Comment by reaperhulk** [comment]
You can build pynacl against a "system" libsodium by passing `SODIUM_INSTALL=system` as an env var. If libsodium isn't in the typical lib/include search paths you'll also need to pass LDFLAGS and CFLAGS of course.
