### ISSUE TITLE
Release 1.3.0 missing manylinux/macos wheels for Python 3.5, 3.6 and 3.7

### ISSUE THREAD

**Issue by touilleMan** [pyca/pynacl#512]
see https://pypi.org/project/PyNaCl/1.3.0/#files

This seems related to #476 

If there is something I can do to help, don't hesitate ;-)

**Comment by reaperhulk** [comment]
We ship abi3 wheels for manylinux and macos so 3.4+ are covered all with a single wheel. If you're not getting a wheel upgrade your `pip`.

**Comment by touilleMan** [comment]
Thanks for the quick answer !

I didn't know about abi3, that's really cool ;-)

**Comment by Upanori7** [comment]
l already update my pip but still facing same error here
