### ISSUE TITLE
Provide bindings for new low-level ed25519 API from recent libsodium

### ISSUE THREAD

**Issue by dciabrin** [pyca/pynacl#529]
Context:

In OpenStack we use PyMSQL [1] to connect to MariaDB.  I'm currently working to extend that library to connect to MariaDB via a MariaDB authentication plugin that is based on Ed25519 [2]. I'm doing so by using PyNaCl.

I'm saying MariaDB authentication is "based on Ed25519" because it has a slight twist in how it implements Ed25519 signature compared to what is specified in RFC 8032 [3]: instead of using a "_32 octets [...] of cryptographically secure random data_" [4] as a private key, it uses the MariaDB user's password. So currently I cannot use the high-level `nacl.signing.SigningKey` to sign MariaDB challenges and authicate users (or I can only authenticate users whose password is 32 bytes long).

Now starting 1.0.17, libsodium exposes all the ed25519 low-level functions needed to implement [5] what MariaDB does for signing challenges, namely: 

- non-clamped ec point multiplication
   
- scalar addition, scalar reduction modulo L (the order of the main subgroup of ed25519)

- scalar multiplication modulo L (although, only available in a subsequent commit)

I would like to propose to bump the version of libsodium in PyNaCl to provide bindings to these new low-level API. I've split that request in two PR:

- #527 to bump the version of libsodium to 1.0.17, plus a single additional commit from 1.0.17+ that exposes scalar multiplication.

- #528 to provide bindings in PyNaCl, along with some unit tests.

I'm not sure whether it is acceptable to use a version of libsodium that is slightly above 1.0.17 (due to the additional commit)? The rational for me proposing that is that it's a minor commit that complements all the modulo arithmetic that went in 1.0.17, and that it is mandatory for me to implement mariadb's auth_ed25519.

Thanks!

[1] https://github.com/PyMySQL/PyMySQL
[2] https://github.com/MariaDB/server/tree/10.4/plugin/auth_ed25519
[3] https://tools.ietf.org/html/rfc8032
[4] https://tools.ietf.org/html/rfc8032#section-5.1.5
[5] https://gist.github.com/dciabrin/aa761dadd8fef8b9c5956944666bb447

**Comment by dciabrin** [comment]
FTR I closed #527 in favour of #533 to bump to 1.0.17 only, and updated #528 to only provide binding for the API exposed in 1.0.17.
For the time being I can workaround not having scalar multiplication modulo L, by implementing it with Python's long integer.

**Comment by dciabrin** [comment]
In the end it got implemented via #536 and #528, thanks :)
Before closing it, I was wondering if there is a timeline already for when to expect a new release that would ship those changes?

**Comment by reaperhulk** [comment]
I think we'll be talking about a release soon (@lmctv may have some feelings here since he's the driver of most progress on this project at the moment). The CI changeover was a herculean effort across most of the python cryptographic authority projects and it took essentially all of my attention but I can spare some time again now to look at actual code. And if I never see Windows again I'll be happy.

**Comment by dciabrin** [comment]
Ack, thanks for the feedback. Closing the issue now.

**Comment by dciabrin** [comment]
Hey @lmctv, @reaperhulk

I was wondering whether you guys had a chance to plan the new release already?
Basically I need it in https://github.com/PyMySQL/PyMySQL/issues/786 to implement mariadb Ed25519 authentication for our OpenStack clients.

Thanks!
