### ISSUE TITLE
Upgrade the compiled version on the windows builders to version 1.0.17

### ISSUE THREAD

**Issue by lmctv** [pyca/pynacl#534]
as already suggested by @reaperhulk in #533

**Comment by lmctv** [comment]
@reaperhulk do you think you could find some time to install the new libsodium binaries on the builders?

**Comment by reaperhulk** [comment]
@lmctv this may turn into an azure pipelines migration (with all the attendant complexity) because we need to get off those servers soon. 😢

**Comment by reaperhulk** [comment]
This is now done after an incredible journey that included endless swearing at Windows as well as figuring out how to build 32-bit VS2010 libsodium artifacts in azure pipelines (followed by Frank very helpfully adding those builds to the 1.0.18 release). https://github.com/pyca/pynacl/pull/535
