### ISSUE TITLE
not able to convert a working code from php into python 

### ISSUE THREAD

**Issue by Hamdy** [pyca/pynacl#544]
Hi all
I'm using libsodium in a php code and things working great, however I can't seem to port the code to python, so am wondering if am missing something or misunderstood something

Here's the link on github for the working code (everything is ported OK until line 69)
https://github.com/freeflowpages/freeflow-threebot-login/blob/master/controllers/user/UserController.php#L69

my python code look like 

https://gist.github.com/Hamdy/af4560845206123027bac5b4d728ca00#file-a-py-L60

Starting from line 60 in python code, am stuck
I can't decrypt the message and am not even sure am goign on the right direction 
is the code
```
box = Box(
        private_key.to_curve25519_private_key(),
        user_pub_key.to_curve25519_public_key()
    )

    try:
        decrypted = box.decrypt(ciphertext, nonce)
```
equivalent to 
```
$decryption_key = sodium_crypto_box_keypair_from_secretkey_and_publickey(
            sodium_crypto_sign_ed25519_sk_to_curve25519($freeflowPrivateKey),
            sodium_crypto_sign_ed25519_pk_to_curve25519($userPublicKey)
         );
        $decrypted = sodium_crypto_box_open($cipherText, $nonce, $decryption_key);

```
any suggestions?

**Comment by miguelperez** [comment]
Hi @Hamdy, I am having a similar issue but porting from Ruby. I am using the rbnacl gem. Did you find what your issue was?
