### ISSUE TITLE
crypto_secretstream: different handling of zero-length data in push/pull

### ISSUE THREAD

**Issue by mk-fg** [pyca/pynacl#547]
#### Problem:

crypto_secretstream_xchacha20poly1305_push allows to encrypt zero-length strings, while corresponding pull function fails to decrypt them with `nacl.exceptions.ValueError: Ciphertext is too short` error.

#### Expected result:

Anything encrypted with crypto_secretstream_xchacha20poly1305_push can then be decrypted with pull function, provided that symmetric key and data is correct.

I.e. either error will be raised on zero-length encryption attempt, or no error raised on decryption, compared to how it currently works.

#### Actual result:

One-way encryption or silent data corruption - push encrypts without any issues, but subsequent decryption always fails, leaving any encrypted data inaccessible.

#### How to reproduce:

Run example code linked by @mmerickel in #345 currently available at this URL:
https://gist.github.com/mmerickel/aee97620e92f4d73bb3e2ea297e7e8b7
...but with data size that aligns exactly with used block size, resulting in last data block being zero-length.

E.g. by running nacl_streams.py script from there like this:
`rm -f foo && dd if=/dev/urandom of=foo bs=20K count=1 && python nacl_streams.py foo`

Script runs encrypt + decrypt round-trip, which results in `nacl.exceptions.ValueError: Ciphertext is too short` error on decryption step, with expected result of successul decryption.

Tested with pynacl 1.3.0 installed from ArchLinux repos, commit log doesn't seem to mention any relevant changes since then, unless I missed them.

**Comment by insasho** [comment]
The maintainer of libsodium confirms this is a bug in the Python bindings (https://github.com/jedisct1/libsodium/issues/916).

**Comment by fhriley** [comment]
This is a problem for all data that is a multiple of chunk_size, i.e. `len(data) % chunk_size == 0`.

**Comment by mmerickel** [comment]
@fhriley are you planning to send a PR for this?

**Comment by fhriley** [comment]
> @fhriley are you planning to send a PR for this?

[I did.](https://github.com/pyca/pynacl/pull/575)

**Comment by mmerickel** [comment]
Oops I’m sorry I dunno why GitHub didn’t link to the PR. I only saw the linked commits in your fork.
