### ISSUE TITLE
Manylinux1 wheels for Python > 3.4

### ISSUE THREAD

**Issue by lelit** [pyca/pynacl#562]
On PyPI there are manylinux1 wheels for Python 2.7 and 3.4, while for more recent snakes only Windows binaries are available.

Is there any particular reason? This makes more and more difficult to use the package in environments lacking the C compiler toolchain (like _slim_ Docker images).

**Comment by alex** [comment]
https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-python-3-5-on-linux-or-macos

**Comment by lelit** [comment]
I see, you are right, sorry for missing the FAQ.
