### ISSUE TITLE
Usability issues found in 2017

### ISSUE THREAD

**Issue by Iiridayn** [pyca/pynacl#564]
https://www.ieee-security.org/TC/SP2017/papers/161.pdf published in 2017 - not sure if you've already addressed these or are familiar with the paper - found a few usability issues with the documentation when asking developers to write some sample code using the library. Might be worth addressing if not already fixed :).

**Comment by reaperhulk** [comment]
We've talked with the authors several times and improved our documentation a bit. One issue with the original study is that we actually had no X509 verification layer (and still don't). That's an ongoing desire for us, but no one has stepped up to do the actual (large amount of) work yet. If there's anything you think can be improved in the docs we're always happy to take PRs for that!
