### ISSUE TITLE
Question PublicKey & PrivateKey of size=16, length=44

### ISSUE THREAD

**Issue by jalanga** [pyca/pynacl#571]
Hi,
I want to generate PrivateKey and PublicKey in python for wireguard.
I changed your code and set the size to 16 for `PublicKey`, `PrivateKey`, also the seed_size=16, and I set
```
crypto_scalarmult_BYTES = 16
crypto_scalarmult_SCALARBYTES = 16
```

Seems to worked fine, but after 2-3-4 generations of keys, I get and error
`| *** Error in `/usr/local/bin/python': free(): invalid next size (fast): 0x00007efbf8101980 ***`

The line of the error is in the method `crypto_scalarmult_base(n)` at the return `return ffi.buffer(q, crypto_scalarmult_SCALARBYTES)[:]`

I searched a lot your lib, also libsodium,  and I can't find the fault.

**Comment by alex** [comment]
You can't simply change teh size of internal constants and expect it to work.

**Comment by sae13** [comment]
Soo cant I use this package for wireguard keys?
