### ISSUE TITLE
New release to publish recent development 

### ISSUE THREAD

**Issue by dciabrin** [pyca/pynacl#573]
Currently PyNaCl is stuck at version 1.3.0 on PyPi, which has been released on 2018.
There has been a lot of development in 2019 and it would be greatly appreciated to capture that into a new release (1.4.0?).

Selfishly speaking, #529 exposed a couple of new functions from newly imported libsodium 1.0.18, and I depend on a new release to push a feature in PyMySQL [1]

This issue aims at discussing what's needed for a new release to happen.

Thanks! 

[1] https://github.com/PyMySQL/PyMySQL/pull/791

**Comment by maqp** [comment]
On a related side-note, the [changelog](https://pynacl.readthedocs.io/en/stable/changelog/) lists none of the features implemented after 1.3.0 was released, have they been listed elsewhere?

**Comment by reaperhulk** [comment]
I'll be doing a release this week. To my knowledge all 1.4.0 features are listed in the CHANGELOG.

**Comment by reaperhulk** [comment]
Done!
