### ISSUE TITLE
libsodium binaries shipped with 1.4.0 wheels fail to load on macOS High Sierra

### ISSUE THREAD

**Issue by studioj** [pyca/pynacl#594]
Seems like a similar problem as this one.

https://github.com/pyca/cryptography/issues/5215

to reproduce 

```
pip install pynacl==1.4.0

python -c "import nacl.bindings"
```

Luckily the same maintainers over here => solution is at hand :-) i'll lock my requirements below 1.4 for now

eager to validate fixes

**Comment by reaperhulk** [comment]
Well this should read libsodium, but yes this will be exactly the same problem. Sigh.

**Comment by reaperhulk** [comment]
@studioj if I get you a fixed wheel in the next few min can you test it?

**Comment by studioj** [comment]
lol prepping for bed :-) here long due bed time ... but i can wait yet another 20 mins if required :-) otherwise it'll be first thing in the morning

**Comment by reaperhulk** [comment]
This job will hypothetically fix it: https://github.com/pyca/pynacl/actions/runs/115171107

I'll link the macOS files once it finishes in the next few minutes.

**Comment by reaperhulk** [comment]
[3.8 zip](https://github.com/pyca/pynacl/suites/717288675/artifacts/7064644) and [2.7 zip](https://github.com/pyca/pynacl/suites/717288675/artifacts/7064643)

**Comment by studioj** [comment]
#figuring_out _how_to_install_custom_wheels and to download them on a remote pc ... gimme a sec

**Comment by studioj** [comment]
![image](https://user-images.githubusercontent.com/22102283/82847585-3c0bcc80-9eef-11ea-87c0-d6964bac2d6d.png)

Thats it

**Comment by reaperhulk** [comment]
Should be fine. Thanks for checking! I'll push fixed wheels momentarily.

**Comment by reaperhulk** [comment]
Fixed!

**Comment by studioj** [comment]
I like the branch name btw :-)

**Comment by studioj** [comment]
thx @reaperhulk  @alex 
double verified on multiple machines (y)
