### ISSUE TITLE
verify() with detached key should verify the size of the key

### ISSUE THREAD

**Issue by simonlindholm** [pyca/pynacl#598]
`VerifyKey.verify(smessage, signature)` concatenates `signature + smessage` and passes this to NaCl. This is a bit of a footgun: if the library user accepts both signature and smessage from untrusted sources, and does not verify that `len(signature) == nacl.bindings.crypto_sign_BYTES`, an attacker is able to spoof a signature for a suffix of a valid message.

**Comment by reaperhulk** [comment]
We should validate this, yes. Would you be willing to supply a PR?

**Comment by simonlindholm** [comment]
Sure, done: #600. (Some instructions in the README about how to build the project and run tests would have been lovely; after a while of staring at the CI config I figured out something that kinda-sorta works but involves manually copying changes over to .tox/py37/lib/python3.7/site-packages/...)

**Comment by reaperhulk** [comment]
If you just run `tox -e py37` it will copy any changes you make into the env automatically, but sounds like we probably do need to write some docs there.
