### ISSUE TITLE
crash on low level bindings for ed25519

### ISSUE THREAD

**Issue by steffensanwald** [pyca/pynacl#599]
Version 1.4 of pynacl adds low level bindings for ed25519 operations. 
When one of the following methods from file nacl/bindings/crypto_scalarmult.py:

- crypto_scalarmult_ed25519_base(n)
- crypto_scalarmult_ed25519_base_noclamp(n)

is called with n=b'\x00'*32, the Unexpected library error is thrown. 
I'm aware that multiplying with zero is a corner case. 
However, in my understanding the curve should still be able to handle it and return the valid result of an encoded 1.

**Comment by reaperhulk** [comment]
`crypto_scalarmult_ed25519_base` is documented as returning -1 if `n` is zero in libsodium: https://libsodium.gitbook.io/doc/advanced/point-arithmetic

The actual function does calculate a result into `q` and then returns -1 to denote the special value (https://github.com/jedisct1/libsodium/blob/927dfe8e2eaa86160d3ba12a7e3258fbc322909c/src/libsodium/crypto_scalarmult/ed25519/ref10/scalarmult_ed25519_ref10.c#L74). However, that result is *not* the identity element so we don't want to be returning it.
