### ISSUE TITLE
Update libsodium to 0.5+

### ISSUE THREAD

**Issue by jvarho** [pyca/pynacl#61]
Changelog:

* Version 0.5.0
 - sodium_mlock()/sodium_munlock() have been introduced to lock pages
in memory before storing sensitive data, and to zero them before
unlocking them.
 - High-level wrappers for crypto_box and crypto_secretbox
(crypto_box_easy and crypto_secretbox_easy) can be used to avoid
dealing with the specific memory layout regular functions depend on.
 - crypto_pwhash_scryptsalsa208sha256* functions have been added
to derive a key from a password, and for password storage.
 - Salsa20 and ed25519 implementations now support overlapping
inputs/keys/outputs (changes imported from supercop-20140505).
 - New build scripts for Visual Studio, Emscripten, different Android
architectures and msys2 are available.
 - The poly1305-53 implementation has been replaced with Floodyberry's
poly1305-donna32 and poly1305-donna64 implementations.
 - sodium_hex2bin() has been added to complement sodium_bin2hex().
 - On OpenBSD and Bitrig, arc4random() is used instead of reading
/dev/urandom.
 - crypto_auth_hmac_sha512() has been implemented.
 - sha256 and sha512 now have a streaming interface.
 - hmacsha256, hmacsha512 and hmacsha512256 now support keys of
arbitrary length, and have a streaming interface.
 - crypto_verify_64() has been implemented.
 - first-class Visual Studio build system, thanks to @evoskuil
 - CPU features are now detected at runtime.

**Comment by malthe** [comment]
@Zah6ooheew if you don't mind then I'll cherry-pick from your branch and update it to the latest libsodium i.e. https://github.com/reaperhulk/pynacl/tree/fix-120.

**Comment by Zah6ooheew** [comment]
On Tue, Jan 27, 2015 at 08:59:37AM -0800, Malthe Borch wrote:
> @Zah6ooheew if you don't mind then I'll cherry-pick from your branch and update it to the latest libsodium i.e. https://github.com/reaperhulk/pynacl/tree/fix-120.
> 

Go for it. As you can tell from my branch I lost interest around the
time i realized that mlock and munlock were going to be a beast to
implement.

**Comment by malthe** [comment]
@Zah6ooheew gotcha. I'm hoping that someone else deals with that part of the update, but I got your changeset working against the updated library version and wrote some tests, too. I actually submitted this work as a pull request against @reaperhulk's branch.

**Comment by dstufft** [comment]
I think this can be closed now with #121 being merged.
