### ISSUE TITLE
Revise documentation and document alternative constructions for secretbox and sealedbox if any

### ISSUE THREAD

**Issue by evilaliv3** [pyca/pynacl#611]
Looking at some issues talking about xchacha20, chacha20 and salsa20 i started wondering if PyNacl offers the possibility to select alternative constructions for secretboxes and sealedboxes.

Specifically i would like if you could clarify on the following specific questions:
1. which is the alghoritm used by default in pynacl  for the implementation of this kind of SecretBox?
2. is there any possibilty to vary this choice in pynacl?
3. in case of affirmative answer to 2 what is the choice that your team advise both in relation to considerations of security and performance

I consider this same clarification useful for SealedBox.

I would like as well to ask if the alghorithm documented in https://pynacl.readthedocs.io/en/stable/secret/ is up to date. The document states that the alghoritm used for secretbox is Salsa20 but actually i think that the latest libsdodium is using by default xchacha20. 

Thank you so much for your work!

\cc @reaperhulk @alex

**Comment by reaperhulk** [comment]
secretbox calls `crypto_secretbox` and uses XSalsa20+Poly1305 (https://libsodium.gitbook.io/doc/secret-key_cryptography/secretbox)

sealedbox calls `crypto_box_seal` and uses X25519 and XSalsa20+Poly1305.

There is no algorithmic choice available because these APIs are opinionated functions provided by libsodium. We should update the docs on our end because they're wrong, thanks for pointing that out. If you send a PR we'd be happy to review and merge!

**Comment by evilaliv3** [comment]
Thank you @reaperhulk!

I was starting making a pull request but i actually discovered that the codebase was already fixed 17 month ago by @LeeSmet  in relation to this error: https://github.com/pyca/pynacl/commit/1b5efe993a86d9dc72045e6bcdb9cc4109c04ede

I guess that patch or even before the documentation on read the docs is failing to update. Would you please notify it to who is mantaining the read the docs account so that they could recheck which is the reasons of the update failure?

**Comment by reaperhulk** [comment]
Ugh, yep we had a rtd integration problem that has been secretly there for 18+ months. I've added the proper webhooks and updated a few configs and it's rebuilding now. I'll close this once I see the proper docs load.
