### ISSUE TITLE
Sign PyPI releases

### ISSUE THREAD

**Issue by maltfield** [pyca/pynacl#614]
**Describe the bug**

When a user downloads this python module using `pip`, there is no cryptographic authenticity or integrity validation to protect the user from a MITM attack.

Therefore, this project is making any other projects that obtain the `PyNaCl` module via `pip` in their build process vulnerable to a [watering hole attack](https://en.wikipedia.org/wiki/Watering_hole_attack).

**Expected behavior**

A developer should have a mechanism to cryptographically verify the integrity and authenticity of this package when obtaining it through `pip`.

**To Reproduce**

`pip install PyNaCl`

**Additional context**

Possible solutions include:

1. Using the [`--sign` argument](https://twine.readthedocs.io/en/latest/#why-should-i-use-this) of `twine` when uploading packages to PyPI

1. Publishing a cryptographically signed document (ideally using `gpg`) listing the hashes for all packages uploaded to PyPI, which users can then pass into `pip` using the [`--hash` argument](https://pip.pypa.io/en/stable/reference/pip_install/#hash-checking-mode)

**Comment by alex** [comment]
We upload signatures on the sdists.

pip doesn't check signatures anyways though.

GPG is not a package signing system: https://caremad.io/posts/2013/07/packaging-signing-not-holy-grail/

**Comment by maltfield** [comment]
So this request is primarily for developers that use `PyNaCl` in their build process.

Currently there is *no* way for a developer verify the `PyNaCL` package wasn't modified by an intermediary. By signing the package, you'd enable developers to update their build-scripts to download both the package and the detached signature, verify, then only proceed with the install if the signature is valid.

```
user@disp569:~$ wget https://files.pythonhosted.org/packages/9d/57/2f5e6226a674b2bcb6db531e8b383079b678df5b10cdaa610d6cf20d77ba/PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl 2>&1 | tail -n2
2020-08-10 00:48:13 (222 KB/s) - ‘PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl’ saved [961075/961075]

user@disp569:~$ wget https://files.pythonhosted.org/packages/9d/57/2f5e6226a674b2bcb6db531e8b383079b678df5b10cdaa610d6cf20d77ba/PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl.asc 2>&1 | tail -n2
2020-08-10 00:48:19 ERROR 404: Not Found.

user@disp569:~$ 
```

With due respect, PGP does work. There's many ways you can publish your fingerprint and key across many locations to make it easy for users to find and TOFU (then pin your fingerprint and/or key into their build tools). As for the risks of TOFU, they're mostly eliminated if you publish your fingerprint in many distinct domains. It's much less likely that an attacker will be able to compromise github.com to modify your `KEYS` file *and* your account on keybase.io *and* your project's description on PyPI.org *and* your project's website *and* the keys.openpgp.org keyserver.

Please reconsider signing your package for downstream developers like myself. Until then, I simply cannot use your software in my software as there's no means for me to verify its integrity and authenticity.
