### ISSUE TITLE
PyNaCl on Docker v2

### ISSUE THREAD

**Issue by Donrskbb** [pyca/pynacl#626]
Previous ticket was closed before i could response but here is my ticket again with more info about the error.

How to get PyNaCl working on a docker/container?
Idk what to do anymore. All bots just doesnt reconise the lib.This is the error

```py
Guild List:
- Casual_Gaming_Dad
Bound to text channels:
- Casual_Gaming_Dad/🎶┃muziek-aanvragen
Autojoining voice channels:
- Casual_Gaming_Dad/🎶┃ Lounge
Attempting to join Casual_Gaming_Dad/🎶┃ Lounge
[ERROR:bot] Failed to join Casual_Gaming_Dad/🎶┃ Lounge
427717508359782400/Donrskbb # 0007: -summon
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
File "/home/container/musicbot/bot.py", line 2815, in on_message
response = await handler(**handler_kwargs)
File "/home/container/musicbot/bot.py", line 1929, in cmd_summon
player = await self.get_player(author.voice.channel, create=True, deserialize=self.config.persistent_queue)
File "/home/container/musicbot/bot.py", line 421, in get_player
voice_client = await self.get_voice_client(channel)
File "/home/container/musicbot/bot.py", line 386, in get_voice_client
return await channel.connect(timeout=60, reconnect=True)
File "/home/container/discord/abc.py", line 1097, in connect
voice = VoiceClient(state=state, timeout=timeout, channel=self)
File "/home/container/discord/voice_client.py", line 90, in __init__
raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
```

And as you can see PyNaCl is installed:
![image](https://user-images.githubusercontent.com/65772844/92934421-c1d46900-f447-11ea-896f-b1601ceda93e.png)

All the hosts i asked they said you cant host musicbots here bcs we cant get PyNaCl working on a docker.

![image](https://user-images.githubusercontent.com/65772844/92935705-6efbb100-f449-11ea-986e-f71db00a29cf.png)

**Comment by reaperhulk** [comment]
Showing us a screenshot of Windows file explorer is not a useful metric for what is and is not installed in a python environment. This project is also installed successfully hundreds of thousands of times per day, so a screenshot saying "that library isn't installable" is both easily falsifiable and also singularly unhelpful in debugging your actual problem.

If you'd like us to take a closer look at this please give us a Dockerfile that reproduces the issue. In the mean time here's one that works just fine

```
FROM ubuntu:focal
RUN apt-get update && apt-get install -yf python3-dev build-essential python3 python3-venv
RUN python3 -m venv venv
RUN venv/bin/pip install pynacl
```

Building that a `venv/bin/pip list` to list the contents of the virtualenv gives:

```
root@830a2ddd39e6:/# venv/bin/pip list
Package       Version
------------- -------
cffi          1.14.2 
pip           20.0.2 
pkg-resources 0.0.0  
pycparser     2.20   
PyNaCl        1.4.0  
setuptools    44.0.0 
six           1.15.0 
```

and PyNaCl imports as expected

```
root@830a2ddd39e6:/# venv/bin/python -c "from nacl import __version__;print(__version__)"   
1.4.0
```

**Comment by Donrskbb** [comment]
The install runs fine but it cannot find it.

**Comment by reaperhulk** [comment]
"it cannot find it" is not a debuggable problem. Please provide a method of reproducing this.
