### ISSUE TITLE
manylinux wheels missing for py38/py39

### ISSUE THREAD

**Issue by ssbarnea** [pyca/pynacl#638]
Apparently there are no manylinux wheels builded for more recent pythons like py38 or py39.

**Comment by alex** [comment]
https://cryptography.io/en/latest/faq.html#why-are-there-no-wheels-for-python-3-6-on-linux-or-macos

**Comment by ssbarnea** [comment]
Thanks, and that is why installing pynacl inside alpine containers fails since this morning, with pynacl failing to compile. Yesterday it was working.

Try `pip install pynacl` on it, and it will fail trying to compile it, clearly not trying to use a binary.

**Comment by reaperhulk** [comment]
abi3 wheels don’t work on alpine because it uses a different libc than other Linux distributions. PyNaCl has always required compilation on alpine

**Comment by ssbarnea** [comment]
I supposed it was something like that. Still this morning the compilation started to fail, it did like this for a number of hours but now it seems to be working.

The original container was building was supposed to re-use system py3-pynacl to avoid compilation but for some weird reason (like related to pep-517 and build-isolation), pip decides to build it.
