### ISSUE TITLE
Previously fixed error, but on new version of python

### ISSUE THREAD

**Issue by nosnowowie93347** [pyca/pynacl#640]
This error here: https://github.com/pyca/pynacl/issues/597 was fixed for Python 3.8

I am now getting it in 3.9

here's the exact console window showing error
![image](https://user-images.githubusercontent.com/65568190/99252460-daecf380-27c3-11eb-87b3-1a486f1f3de2.png)
if you need more let me know in the comments

**Comment by nosnowowie93347** [comment]
it could just be python 3.9 is too new for this module

**Comment by reaperhulk** [comment]
This project ships abi3 artifacts that work on any Python 3.5+ for Windows. However, this requires upgrading your pip.
