### ISSUE TITLE
how to enable 64 bytes private key 

### ISSUE THREAD

**Issue by yurenji** [pyca/pynacl#644]
I noticed the PrivateKey has a validation on the bytes size: https://github.com/pyca/pynacl/blob/master/src/nacl/public.py#L88, which is 32 by default. 

I wonder is there anyway to create a PrivateKey with 64 bytes? Maybe change the default size by setting an env variable? 

more details about my problem: https://github.com/michaelhly/solana-py/issues/47 ( Solona is an application I am testing and it has a dependency on pynacl)

**Comment by alex** [comment]
No, this code implements one cryptographic algorithm which has 32 byte keys.
