### ISSUE TITLE
Error when decryting 

### ISSUE THREAD

**Issue by Shivanshu10** [pyca/pynacl#658]
I wrote a program to share files on local network using PyNacl the encrytion works for small files but seems to break for long files, could not find any solution for this on internet
```
nacl.exceptions.CryptoError: An error occurred trying to decrypt the message
```

**Comment by alex** [comment]
You have not provided enough information to debug this. We need a minimal reproducer that demonstrates a bug.

**Comment by Shivanshu10** [comment]
Fixed it was some issue in implementing file share. Thanks
