### ISSUE TITLE
PyNaCl 1.4.0 and Python 3.4 in PyPI

### ISSUE THREAD

**Issue by StykMartin** [pyca/pynacl#678]
Hello,

Can you please provide manylinux WHL for Python 3.4 for PyNaCL 1.4.0? Accordingly to metadata, this release was still supported on Python 3.4
```
Requires: Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
```

The rest of the Python 3 versions have the WHL there.

**Comment by reaperhulk** [comment]
We won't be shipping new wheels for 1.4 at this point, sorry
