### ISSUE TITLE
crypto_generichash

### ISSUE THREAD

**Issue by adamcaudill** [pyca/pynacl#71]
It would be useful to expose the `crypto_generichash` method (Blake2b).

Working on a project now that calls for Blake2b, but that doesn't seem to be exposed anywhere.

**Comment by lmctv** [comment]
Very late in noticing your issue. Would you mind checking if my PR #201 fulfills your requirements?
Thank you.

**Comment by lmctv** [comment]
I think #217 closes this issue too.
