### ISSUE TITLE
Wheel support for Universal2

### ISSUE THREAD

**Issue by mcclurem** [pyca/pynacl#713]
Apple silicon Macs are pretty much the only kind of Mac you can buy now, can we please enable either a universal2 or arm-specific wheel for macOS?

**Comment by reaperhulk** [comment]
The next release will ship macOS arm64 wheels. They may or may not be `universal2` due to CI challenges.

**Comment by reaperhulk** [comment]
Update: they will be universal2

**Comment by reaperhulk** [comment]
Shipped in 1.5.0.

**Comment by rkhwaja** [comment]
Maybe you should update the cffi dependency to >=1.15.0 for macosx, that's the version where they added support for arm64
