### ISSUE TITLE
release v0.3.0

### ISSUE THREAD

**Issue by warner** [pyca/pynacl#73]
I'd like to see a new release soon. I'm thinking we should block on #72, #52, and the docs overhaul (removing autodocs) that @Ayrx is working on to let the #52 branch pass. How's that sound?

**Comment by imthedoctor** [comment]
Hey guys,

Are there plans for an 0.3.0 any time soon? I use pynacl in an API client library and the vast majority of my users run into installation/import issues related to CFFI that are mostly resolved by commit d4d3175589b892f6ea7c22f466e0e223853516fa. It'd be really nice to have a version with that commit in PyPI.

**Comment by alex** [comment]
I think we shoudl get #121 done and the do a release? None of the other stuff in this ticket should be blockers.

**Comment by warner** [comment]
That's what I was thinking. I'll try to test and merge that one this afternoon.

**Comment by alex** [comment]
Awesome -- FWIW I think it's fine testing wise, we just need to verify that
the code correctly matches upstream (sorry @reaperhulk -- trust is for
people who don't work on crypto)

On Tue, Mar 3, 2015 at 1:58 PM, Brian Warner <notifications@github.com>
wrote:

> That's what I was thinking. I'll try to test and merge that one this
> afternoon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/pynacl/issues/73#issuecomment-77045432>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
(The easiest way to do that is get the official tar.gz, check out
reaperhulk's branch, unpack the tar.gz over that branch, and verify that
`git diff` is empty)

On Tue, Mar 3, 2015 at 2:01 PM, Alex Gaynor <alex.gaynor@gmail.com> wrote:

> Awesome -- FWIW I think it's fine testing wise, we just need to verify
> that the code correctly matches upstream (sorry @reaperhulk -- trust is for
> people who don't work on crypto)
>
> On Tue, Mar 3, 2015 at 1:58 PM, Brian Warner <notifications@github.com>
> wrote:
>
>> That's what I was thinking. I'll try to test and merge that one this
>> afternoon.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pyca/pynacl/issues/73#issuecomment-77045432>.
>>
>
>
>
> --
> "I disapprove of what you say, but I will defend to the death your right
> to say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
> "The people's good is the highest law." -- Cicero
> GPG Key fingerprint: 125F 5C67 DFE9 4084
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment]
Should probably decide on what to do about #110, even if the answer is "we're going to just keep ``nacl.c``".

**Comment by warner** [comment]
#121: yup, verified to match upstream 1.0.1 and landed.

#110: oh yeah, I'd forgotten about that (funny, since I was the one who made those API changes in the first place..). Hm, moving the low-level module to a new name *does* sound like a good idea. Anyone object?

**Comment by dstufft** [comment]
I personally have no objection, and it's probably safer to do.

**Comment by Ayrx** [comment]
Do we care about breaking backwards compat with the change?

**Comment by dstufft** [comment]
One more release sensitive issue is: https://github.com/pyca/pynacl/pull/98, if we're going to change that we probably want to do it before we release v0.3.0 since that API was added, if not we probably want to close that PR.

**Comment by dstufft** [comment]
@Ayrx we already broken compat by swapping the order of the arguments for sk and pk because when I originally wrote that API I somehow reversed the order from the order of the "standard" functions in NaCl. So 0.3.0 already breaks compat, renaming would just make it fail more obviously.

**Comment by Ayrx** [comment]
Cool. No objections then.

**Comment by alex** [comment]
I'm not in favor of #98 -- we use the std python names for things.

**Comment by dstufft** [comment]
I'm fine with closing #98, I think I lean towards that option as well. Just figured if we *were* going to merge it, doing it now makes more sense.

**Comment by warner** [comment]
Ok, #98 is WONTFIXed, #121 is done, #110 is done. I'd kind of like to see #127 in 0.3.0 (adds some type-checking to improve error messages). But I think there's nothing else. When we decide (one way or the other) about #127, I intend to do:


* `git tag v0.3.0; git push; git push --tags`
* `python setup.py sdist register upload`

Any objections, or anything I should plan to do differently?

**Comment by dstufft** [comment]
I'd prefer if you used twine instead of ``setup.py register upload`` but otherwise that seems correct. I'm ok with #127 as well, I'd merge it myself but tests haven't passed.

**Comment by warner** [comment]
Oh, incidentally, I should have included `edit src/nacl/__init__.py to bump version=`, but we pre-bumped it last June "so we don't forget".

I don't know twine: I'll look it up.

Yeah, travis is running very slowly tonight, ~1hr from commit to complete.

**Comment by dstufft** [comment]
Twine is just an upload thing that lets you decouple sdist creation from upload, and it also ensures to only talk to PyPI via verified TLS.

Basically you just do:

```
$ python setup.py sdist
$ twine upload dist/*
```

Alternatively you can add the ``-s`` flag to twine if you want to sign the release with GPG.

**Comment by warner** [comment]
Found it. Twine sounds good. I assume it does the `register` as well as the `upload`?

If you add a +1 to #127, I'll merge it if/when the tests finish passing.

**Comment by dstufft** [comment]
Yea (well actually PyPI auto registers on upload after the first time you've registered so it doesn't need to do anything).

**Comment by warner** [comment]
Ok, #127 is landed. I'll start the release process.

**Comment by warner** [comment]
Release is done!
* tag `v0.3.0` is commit `74ef3bac181fde4bc08f5aa98d08496c879e37fe`
* pypi: https://pypi.python.org/pypi/PyNaCl/
* tarball is signed with a new code-signing GPG key I created, short=`4096R/65497810`, fingerprint=`5810 F125 7F8C F753 7753  895A 8633 33C2 6549 7810`

**Comment by Ayrx** [comment]
Congrats! An announcement to the cryptography-dev mailing list may be in
order. :)

**Comment by imthedoctor** [comment]
Wow, I really didn't think this would get done less than 12 hours after I posted. Way to go guys, this makes my life so much easier. :)
