### ISSUE TITLE
check-manifest gets confused by docs/_build

### ISSUE THREAD

**Issue by joernheissler** [pyca/pynacl#732]
First build the docs with `tox -e docs`, then do meta checks:
```
$ tox -e meta
...
meta run-test: commands[2] | check-manifest . --ignore .travis.yml
lists of files in version control and sdist do not match!
missing from VCS:
  docs/_build/html/_downloads/44b911a7f4a40c3279763302410cf51d/argondriver.py
  docs/_build/html/_images/ed25519.png
  docs/_build/html/_static/ed25519.png
  docs/_build/html/_static/file.png
  docs/_build/html/_static/minus.png
  docs/_build/html/_static/plus.png
```

I suspect that `MANIFEST.in` needs a change, e.g. `exclude docs/_build/**`. But I'm not familiar with MANIFEST and it doesn't behave how I understand the docs.

**Comment by reaperhulk** [comment]
Yeah just need to add a `prune docs/_build` into the `MANIFEST.in` to have it automatically remove that.
