### ISSUE TITLE
Building wheels for python 3.9

### ISSUE THREAD

**Issue by fruch** [pyca/pynacl#735]
I'm doing builds base on fedora34, which has python3.9, both on aarch64 and x86_64, and not having wheel for those, is slowing down a lot builds with qemu based cross compilation (building docker for both architectures)

**Comment by reaperhulk** [comment]
Our wheels work fine on python 3.9 for x86_64. aarch64 wheels will be coming in the next release.

**Comment by alex** [comment]
https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-my-python3-x-version
