### ISSUE TITLE
Wheels uploaded only for Python 3.6

### ISSUE THREAD

**Issue by ccordoba12** [pyca/pynacl#744]
The new 1.5.0 release has only wheels for Python 3.6 and not for other Python versions in PyPI:

https://pypi.org/project/PyNaCl/#files

**Comment by reaperhulk** [comment]
https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-my-python3-x-version

**Comment by ccordoba12** [comment]
Thanks for the fast response!
