### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by Kasiso** [pyca/pynacl#755]
Collecting pynacl
  Using cached PyNaCl-1.5.0.tar.gz (3.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.4.1 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from pynacl) (1.15.0)
Requirement already satisfied: pycparser in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from cffi>=1.4.1->pynacl) (2.21)
Building wheels for collected packages: pynacl
  Building wheel for pynacl (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pynacl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [188 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-3.10
      creating build/lib.linux-aarch64-3.10/nacl
      copying src/nacl/hash.py -> build/lib.linux-aarch64-3.10/nacl
      copying src/nacl/__init__.py -> build/lib.linux-aarch64-3.10/nacl
      copying src/nacl/exceptions.py -> build/lib.linux-aarch64-3.10/nacl
      copying src/nacl/encoding.py -> build/lib.linux-aarch64-3.10/nacl
      copying src/nacl/utils.py -> build/lib.linux-aarch64-3.10/nacl
      copying src/nacl/signing.py -> build/lib.linux-aarch64-3.10/nacl
      copying src/nacl/secret.py -> build/lib.linux-aarch64-3.10/nacl
      copying src/nacl/hashlib.py -> build/lib.linux-aarch64-3.10/nacl
      copying src/nacl/public.py -> build/lib.linux-aarch64-3.10/nacl
      creating build/lib.linux-aarch64-3.10/nacl/pwhash
      copying src/nacl/pwhash/__init__.py -> build/lib.linux-aarch64-3.10/nacl/pwhash
      copying src/nacl/pwhash/_argon2.py -> build/lib.linux-aarch64-3.10/nacl/pwhash
      copying src/nacl/pwhash/argon2id.py -> build/lib.linux-aarch64-3.10/nacl/pwhash
      copying src/nacl/pwhash/argon2i.py -> build/lib.linux-aarch64-3.10/nacl/pwhash
      copying src/nacl/pwhash/scrypt.py -> build/lib.linux-aarch64-3.10/nacl/pwhash
      creating build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_hash.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/utils.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_shorthash.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_kx.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_box.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/randombytes.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_secretstream.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/__init__.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_generichash.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_secretbox.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_scalarmult.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/sodium_core.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_aead.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_core.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_sign.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/bindings/crypto_pwhash.py -> build/lib.linux-aarch64-3.10/nacl/bindings
      copying src/nacl/py.typed -> build/lib.linux-aarch64-3.10/nacl
      running build_clib
      checking build system type... aarch64-unknown-linux-gnu
      checking host system type... aarch64-unknown-linux-gnu
      checking target system type... aarch64-unknown-linux-gnu
      checking for a BSD-compatible install... /data/data/com.termux/files/usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a race-free mkdir -p... /data/data/com.termux/files/usr/bin/mkdir -p
      checking for gawk... gawk
      checking whether make sets $(MAKE)... yes
      checking whether make supports nested variables... yes
      checking whether UID '10408' is supported by ustar format... yes
      checking whether GID '10408' is supported by ustar format... yes
      checking how to create a ustar tar archive... gnutar
      checking whether make supports nested variables... (cached) yes
      checking whether to enable maintainer-specific portions of Makefiles... no
      checking for gcc... aarch64-linux-android-clang
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether the compiler supports GNU C... yes
      checking whether aarch64-linux-android-clang accepts -g... yes
      checking for aarch64-linux-android-clang option to enable C11 features... none needed
      checking whether aarch64-linux-android-clang understands -c and -o together... yes
      checking whether make supports the include directive... yes (GNU style)
      checking dependency style of aarch64-linux-android-clang... none
      checking dependency style of aarch64-linux-android-clang... none
      checking for stdio.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for strings.h... yes
      checking for sys/stat.h... yes
      checking for sys/types.h... yes
      checking for unistd.h... yes
      checking for wchar.h... yes
      checking for minix/config.h... no
      checking whether it is safe to define __EXTENSIONS__... yes
      checking whether _XOPEN_SOURCE should be defined... no
      checking for a sed that does not truncate output... /data/data/com.termux/files/usr/bin/sed
      checking how to run the C preprocessor... aarch64-linux-android-clang -E
      checking for grep that handles long lines and -e... /data/data/com.termux/files/usr/bin/grep
      checking for egrep... /data/data/com.termux/files/usr/bin/grep -E
      checking whether aarch64-linux-android-clang is Clang... yes
      checking whether pthreads work with "-pthread" and "-lpthread"... yes
      checking whether Clang needs flag to prevent "argument unused" warning when linking with -pthread... no
      checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
      checking whether more special flags are required for pthreads... no
      checking for PTHREAD_PRIO_INHERIT... yes
      checking for variable-length arrays... yes
      checking for __wasi__ defined... no
      checking whether to add -D_FORTIFY_SOURCE=2 to CPPFLAGS... yes
      checking whether C compiler accepts -fvisibility=hidden... yes
      checking whether C compiler accepts -fPIC... yes
      checking whether C compiler accepts -fPIE... yes
      checking whether the linker accepts -pie... yes
      checking whether C compiler accepts -fno-strict-aliasing... yes
      checking whether C compiler accepts -fno-strict-overflow... yes
      checking for a broken Xcode version... no
      checking whether C compiler accepts -fstack-protector... yes
      checking whether the linker accepts -fstack-protector... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wall... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra... yes
      checking for clang... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wold-style-declaration... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wold-style-declaration -Wpointer-arith... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wold-style-declaration -Wpointer-arith -Wredundant-decls... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wold-style-declaration -Wpointer-arith -Wredundant-decls -Wrestrict... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wold-style-declaration -Wpointer-arith -Wredundant-decls -Wrestrict -Wshorten-64-to-32... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wold-style-declaration -Wpointer-arith -Wredundant-decls -Wrestrict -Wshorten-64-to-32 -Wsometimes-uninitialized... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wold-style-declaration -Wpointer-arith -Wredundant-decls -Wrestrict -Wshorten-64-to-32 -Wsometimes-uninitialized -Wstrict-prototypes... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wold-style-declaration -Wpointer-arith -Wredundant-decls -Wrestrict -Wshorten-64-to-32 -Wsometimes-uninitialized -Wstrict-prototypes -Wswitch-enum... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wold-style-declaration -Wpointer-arith -Wredundant-decls -Wrestrict -Wshorten-64-to-32 -Wsometimes-uninitialized -Wstrict-prototypes -Wswitch-enum -Wvariable-decl... yes
      checking whether C compiler accepts -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3  -fstack-protector-strong -O3 -pthread -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-qual -Wdiv-by-zero -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wlogical-op -Wmaybe-uninitialized -Wmisleading-indentation -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-type-limits -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wold-style-declaration -Wpointer-arith -Wredundant-decls -Wrestrict -Wshorten-64-to-32 -Wsometimes-uninitialized -Wstrict-prototypes -Wswitch-enum -Wvariable-decl -Wwrite-strings... yes
      checking whether the linker accepts -Wl,-z,relro... yes
      checking whether the linker accepts -Wl,-z,now... yes
      checking whether the linker accepts -Wl,-z,noexecstack... yes
      checking whether segmentation violations can be caught... yes
      checking whether SIGABRT can be caught... yes
      checking for thread local storage (TLS) class... _Thread_local
      thread local storage is supported
      checking whether C compiler accepts -ftls-model=local-dynamic... yes
      checking how to print strings... printf
      checking for a sed that does not truncate output... (cached) /data/data/com.termux/files/usr/bin/sed
      checking for fgrep... /data/data/com.termux/files/usr/bin/grep -F
      checking for ld used by aarch64-linux-android-clang... no
      configure: error: no acceptable ld found in $PATH
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 202, in <module>
          setup(
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wgpafzga/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "setup.py", line 160, in run
          subprocess.check_call(
        File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/data/data/com.termux/files/usr/tmp/pip-install-u9v2z7n9/pynacl_ce8c2c3d91df4b6fb739fe0cb93c5459/src/libsodium/configure', '--disable-shared', '--enable-static', '--disable-debug', '--disable-dependency-tracking', '--with-pic', '--prefix', '/data/data/com.termux/files/usr/tmp/pip-install-u9v2z7n9/pynacl_ce8c2c3d91df4b6fb739fe0cb93c5459/build/temp.linux-aarch64-3.10']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynacl
Failed to build pynacl
ERROR: Could not build wheels for pynacl, which is required to install pyproject.toml-based projects

**Comment by alex** [comment]
It looks like you're trying to cross-compile for android, but you don't have a linker on your path:

```
checking for ld used by aarch64-linux-android-clang... no
configure: error: no acceptable ld found in $PATH
```

is there a reason you think this is a pynacl bug?

**Comment by Kasiso** [comment]
> 
I don't think this is a bug with pynacl, I just want to ask how to fix it

**Comment by alex** [comment]
You've provided _no information_ on your build environment or anything else that might help us debug.

So off the cuff I'd say: wherever you're getting your compiler for cross-compilation, I'd figure out how to get it to give you a linker as well.

**Comment by Kasiso** [comment]
> You've provided _no information_ on your build environment or anything else that might help us debug.
> 
> So off the cuff I'd say: wherever you're getting your compiler for cross-compilation, I'd figure out how to get it to give you a linker as well.

I am using a GNU/Linux environment emulator for Android(Termux).To be honest, I have no idea what else to tell you. If it's not difficult, then you can say that I need to clarify more.

**Comment by Kasiso** [comment]
I found a way to solve this:

$ pkg install clang python libffi openssl libsodium
$ SODIUM_INSTALL=system pip install pynacl
