### ISSUE TITLE
provide wheels for aarch64 & version 1.4.0

### ISSUE THREAD

**Issue by tbugfinder** [pyca/pynacl#759]
My project depends on 3rd party deps pinned to version 1.4.0.
While preparing a ARM based container image, I noticed that version 1.4.0 doesn't provide wheel so the installations takes very long.
Would it be possible to provide ARM wheels for version 1.4.0 in addition to those provided in 1.5.0?

Thanks!

**Comment by alex** [comment]
In general we do not provide support for older releases of pynacl, is there a reason that you cannot upgrade to 1.5.0?

**Comment by tbugfinder** [comment]
Basically my project depends on azure-cli (arm) [1] which is locked on pynacl v1.4.0. 
Therefore the installations on arm64 takes very long to complete.


Ref:
[1] https://github.com/Azure/azure-cli/issues/7368

**Comment by reaperhulk** [comment]
The azure-cli folks should update their dependency as we don't have the resources to support out of date versions here. Looking at that project it seems like they may have numerous out of date dependency issues, but perhaps an explicit issue or a PR modifying their dep set to upgrade to 1.5.0 would actually get merged. Good luck!
