### ISSUE TITLE
n00b: Loading a ed25519 key pair from base64 string

### ISSUE THREAD

**Issue by FrankC01** [pyca/pynacl#771]
Beginner:

Where can I create a ed25519 keypair (public key and private key) from a base64 string or it's decoded bytes?

**Comment by FrankC01** [comment]
That expects 32 bytes, however the keypair is stored, for example:
`AKky78X+ERAnhbshgRVyrC0yfKwLYh6eh0mGS51A893KRWO62jCwbiXK8fTEmp6fJv0uz/1cKhRhJYIbYzRslTw=`

**Comment by reaperhulk** [comment]
That's likely the 64 byte form, which pynacl doesn't directly support loading at this time (see: https://github.com/pyca/pynacl/pull/648)

**Comment by FrankC01** [comment]
Thanks, I'm loading the Signing key just fine now.
