### ISSUE TITLE
Wheels not updated for 3.11.7 on Windows (MinGW)

### ISSUE THREAD

**Issue by PMahar** [pyca/pynacl#810]
Hate to rehash this issue but trying to install PyNaCl on 3.11.7 on MSYS2 fails, stating it can't find ```make```.

Commands tried:
```python3 -m pip install pynacl``` and ```python3 -m pip install -U "nextcord[voice]"```
(Nextcord is a library I'm using for a discord bot, a dependency of which being pynacl)

Errors from those commands, respectively:
![image](https://github.com/pyca/pynacl/assets/56207889/9b6cc56c-4e69-4a50-9d35-e34eef151c56)
![image](https://github.com/pyca/pynacl/assets/56207889/2f2dc322-7b31-47a7-947f-2c62b17deac4)

I've already tried updating ```pip``` with ```pip install --upgrade pip``` and installing ```setuptools``` with ```pip install setuptools```, as recommended here: https://github.com/pyca/pynacl/issues/746.

To verify that ```make``` is, in fact, on my path:
![image](https://github.com/pyca/pynacl/assets/56207889/70b9e02f-5957-427e-b8cc-c4f15f47ed98)

Is there anything we can do about this on our end?

**Comment by alex** [comment]
The wheels we publish are abi3 wheels, they work with all supported versions of python3. If your pip is not automatically installing them, that indicates some issue with your pip (most likely that it's out of date and that your attempt to upgrade it did not work.)

**Comment by PMahar** [comment]
I ran get-pip just now to make sure I had the right version, and it appears to have downloaded 23.3.2, the latest. Still fails with the same issue.

![image](https://github.com/pyca/pynacl/assets/56207889/f09ee5e5-5d81-4b24-84d6-04d9a802ae80)

**Comment by reaperhulk** [comment]
There are no wheels for mingw and we unfortunately have no environments to test this. Assuming libsodium supports mingw then figuring out why it doesn’t find make is the next logical debug step. I’m not at all familiar with this environment though so I can’t provide much assistance.On Jan 16, 2024, at 11:50 PM, Patrick Mahar ***@***.***> wrote:﻿
I ran get-pip just now to make sure I had the right version, and it appears to have downloaded 23.3.2, the latest. Still fails with the same issue.
image.png (view on web)

**Comment by PMahar** [comment]
Gah, I was worried about that, though it's understandable. I'll work with a linux VM for now. Thanks anyway!
